### ISSUE TITLE
Make action compatible with Ubuntu 22.04

### ISSUE THREAD

**Issue by michallepicki** [erlef/setup-beam#116]
A [beta of `ubuntu-22.04` runners](https://github.blog/changelog/2022-05-10-github-actions-beta-of-ubuntu-22-04-for-github-hosted-runners-is-now-available/) is now available. I think the biggest change is that Ubuntu 22.04 uses openssl 3.0, so Ubuntu 20.04 Erlang builds probably won't work there.

I'm opening this issue to start the discussion towards supporting the new runner in the future. Would the builds be provided by `hexpm/bob` (see [relevant issue there](https://github.com/hexpm/bob/issues/112))?

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @michallepicki. Thanks for bringing this up.

What's the status on the compatibility between current OTP and OpenSSL 3.0? (I remember there were discussions around it, at `erlang/otp` but can't remember where we are)

Regarding "the builds... by hexpm/bob", I can't be sure. @ericmj might have a better idea about future plans, since there were talks about deprecating something Erlang-related from bob (or bob entirely (?).

**Comment by michallepicki** [comment]
I'll work on adding Ubuntu 22.04 to bob some time this week ([see issue](https://github.com/hexpm/bob/issues/112)) so hopefully some of the questions will be cleared up.

I was able to build and use erlang/otp from the master branch on Ubuntu 22.04 with only OpenSSL 3.0 present, there was only a warning when building about support being experimental. I don't know if this will change for OTP 25. As to previous OTP versions, I imagine the Erlang/OTP team won't be backporting OpenSSL 3.0 compatibility so maybe some of the older versions will have to be disabled for that runner.

**Comment by paulo-ferraz-oliveira** [comment]
> so maybe some of the older versions will have to be disabled for that runner.

You mean by `setup-beam` itself? I know we restrict some stuff (https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp), but what did you have in mind? Not allowing for a specific Erlang version for Ubuntu-22, for example?

**Comment by michallepicki** [comment]
Yes, but maybe the error users will se when a version will simply not be provided by bob will be good enough, I don't know yet, haven't looked into that yet :)

**Comment by paulo-ferraz-oliveira** [comment]
As long as 1. it's as fully backward compatible **as possible** (even if we have to hack something in the action), 2. doesn't break for existing builds... I'm sure we're Ok with whatever solution is found 👍

**Comment by michallepicki** [comment]
Ubuntu 22.04 Jammy builds are now provided, as I anticipated from OTP 24.2 version only: https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt

**Comment by jordanbcooper** [comment]
Any chance that 22.04 will be supported soon? Dealing with annoying openssl 1.1.1 vs openssl 3.0 issues that I think this will resolve.

**Comment by michallepicki** [comment]
Hi @jordanbcooper , you can install Erlang/Elixir on the `ubuntu-22.04` runner this way for now: 

```
      - name: Install Erlang
        run: |
          curl -Lo erlang.tar.gz https://repo.hex.pm/builds/otp/ubuntu-22.04/OTP-25.0.1.tar.gz
          mkdir erlang
          tar zxf erlang.tar.gz -C erlang --strip-components=1
          erlang/Install -minimal  `pwd`/erlang
          echo "`pwd`/erlang/bin" >> $GITHUB_PATH
          rm erlang.tar.gz

      - name: Install Elixir
        run: |
          curl -Lo elixir.zip https://repo.hex.pm/builds/elixir/v1.13.4-otp-25.zip
          mkdir elixir
          unzip -q -o -d `pwd`/elixir elixir.zip
          echo "`pwd`/elixir/bin" >> $GITHUB_PATH
          rm elixir.zip
```

**Comment by jordanbcooper** [comment]
@michallepicki  Thank you, this is suitable!

**Comment by paulo-ferraz-oliveira** [comment]
Let me prepare a PR in stages... I'll first add 22.04 to the runners, tests and README, and then I'll try to find specific OpenSSL 1 and 3 tests that'll show no regression. (@jordanbcooper, if you want you can show me what's breaking for you - compatibility-wise, and I can try to adapt that to our tests).

**Comment by paulo-ferraz-oliveira** [comment]
I've created #124 to address this. @michallepicki, I'm assuming (Bob-built) 24.2+ only provide OpenSSL 3.0, is that correct? If that's the case (and there's no alternative to choosing a different OpenSSL version - does one even want that?) I believe the PR might be complete, otherwise we should add further tests.

**Comment by michallepicki** [comment]
> I'm assuming (Bob-built) 24.2+ (on Ubuntu 22.04) only provide OpenSSL 3.0, is that correct?
AFAIK these builds are only compatible with OpenSSL 3.0, correct. At least they were built with such configuration. Hexpm/bob was not building OpenSSL previously so it didn't change for its Ubuntu 22.04 Erlang/OTP builds, they are still using dynamically linked OpenSSL provided by the system.

> and there's no alternative to choosing a different OpenSSL version - does one even want that?
I think some people compile Erlang to use statically linked specific versions of OpenSSL, but supporting this would mean duplicating work that hexpm/bob is doing and more. So that a full version could be `24.2-openssl-1.1.0b` or `24.2-openssl-1.1.1p` or `24.2-openssl-3.0.1` or `24.2-openssl-3.0.4` etc. It just doesn't seem to make sense to have to maintain all variants.

As to providing builds compatible with dynamically linked OpenSSL 1 or 3 (so having two variants, e.g. `24.2-openssl-1` and `24.2-openssl-3`, it maybe would make sense if it was possible to install OpenSSL 1 on Ubuntu 22.04 from `apt` to a standard location. But it's not possible, so to have it dynamically linked we'd have to standardize where we require the user to have it installed.

**Comment by paulo-ferraz-oliveira** [comment]
> It just doesn't seem to make sense to have to maintain all variants.

That's what I had in mind, but wanted to confirm.

So it seems that just adding 22.04 to the runners and testing it (I'm not sure we need to include OpenSSL related info in the README) should suffice, right? (as per the linked PR).

Thanks for your input.
