### ISSUE TITLE
Erlang OTP 25 support

### ISSUE THREAD

**Issue by anmlnath** [erlef/setup-beam#117]
Running into this error when using Erlang OTP 25, even after clearing the GitHub CI cache.

Apparently it's related to using a precompiled version of Elixir

```
Running mix local.rebar,--force
  /home/runner/work/_temp/.setup-beam/elixir/bin/mix local.rebar --force
  
  Error: 7.616 [error] beam/beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
  Warning:   lambda already defined for label 749. To fix this, please recompile this module with an OTP 25 compiler.
  
  Error: 7.616 [error] Loading of /home/runner/work/_temp/.setup-beam/elixir/bin/../lib/elixir/ebin/Elixir.Code.Formatter.beam failed: :badfile
  
  ** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
      (elixir 1.13.4) Code.Formatter.locals_without_parens()
      (elixir 1.13.4) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
  Warning:     (elixir 1.13.4) lib/code.ex:1107: Code.quoted_to_algebra/2
  Error: The process '/home/runner/work/_temp/.setup-beam/elixir/bin/mix' failed with exit code 1
  ```

**Comment by paulo-ferraz-oliveira** [comment]
Let me add some tests for 25.0.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/erlef/setup-beam/pull/118: let me see what the results say.

**Comment by anmlnath** [comment]
Thanks. Note that the error is coming from the Erlang 25 + Elixir combination. This is my setup:

```
- uses: erlef/setup-beam@v1
  with:
    otp-version: "25"
    elixir-version: "1.13.4"
```

**Comment by paulo-ferraz-oliveira** [comment]
What's your config.? Is it possible for you to point to the repo. where you have the failing CI?

**Comment by paulo-ferraz-oliveira** [comment]
What OS version?

**Comment by anmlnath** [comment]
OS: `runs-on: ubuntu-latest`

Is the `rebar3-version` required? That's the only difference I see between your version and mine -- other than that I was trying earlier today. Let me try re-running my config.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, Hex building for all the OTP versions takes a while, and then we fetch from it. Maybe you were too fast (?)

No. `rebar3-version` shouldn't be required, but I removed that in the latest combo I added.

**Comment by idyll** [comment]
I think Homebrew is seeing the same issue here maybe: 

https://github.com/Homebrew/homebrew-core/pull/101839

**Comment by paulo-ferraz-oliveira** [comment]
Everything seems fine: https://github.com/erlef/setup-beam/runs/6496388432?check_suite_focus=true#step:3:3 (i.e. I can replicate your issue at least with the small tests we have).

**Comment by anmlnath** [comment]
I did `git commit --allow-empty` and it is working now -- likely just the rebar version over the past 4 hours?

**Comment by paulo-ferraz-oliveira** [comment]
Well, we could try pinpointing a specific `rebar3` version and see if the error surfaces.

**Comment by paulo-ferraz-oliveira** [comment]
From https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt you can see 25.0 was ready "in the morning".

**Comment by paulo-ferraz-oliveira** [comment]
Works fine with 3.18.0, seems: https://github.com/erlef/setup-beam/runs/6496476574?check_suite_focus=true#step:3:5

**Comment by paulo-ferraz-oliveira** [comment]
As per https://repo.hex.pm/builds/elixir/builds.txt, 1.13.4 (Elixir) was available a couple of hours after Erlang, there.

**Comment by anmlnath** [comment]
Thanks Paulo

👍🏻

**Comment by paulo-ferraz-oliveira** [comment]
> I think Homebrew is seeing the same issue here maybe:
>
> https://github.com/Homebrew/homebrew-core/pull/101839

`setup-beam` matches the OS version with OTP (and fetches that from Hex.pm); we then match (in the case of Elixir) Elixir with OTP (and fetch that from Hex.pm). It's possible it was failing and assets were re-uploaded, but unlikely, since I believe firmly that Hex only provides the stuff after its tests (which means compiled against and appropriate OTP version). So this smells more like an internal GitHub CI cache issue.

**Comment by anmlnath** [comment]
I had tried revving the `actions/cache@v2` cache key before opening this issue -- that didn't help at the time.

Doesn't matter now though, since everything is working. Thanks for adding the tests and for the help.

**Comment by paulo-ferraz-oliveira** [comment]
@anmlnath, thing is we've already seen cache stuff happen even after we clear it, which is why I suspect that. It's either that, or the Elixir version used wasn't compiled against the proper Erlang/OTP which is unlikely.

**Comment by paulo-ferraz-oliveira** [comment]
Let me try with the strict version spec, that we created for this very case.

**Comment by paulo-ferraz-oliveira** [comment]
I'll run it against `v1.13.4-otp-25` and `v1.13.4` for the same Erlang/OTP and `rebar3` versions.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/erlef/setup-beam/runs/6497057071?check_suite_focus=true#step:3:17 🤣 (a limitation I myself coded)

**Comment by paulo-ferraz-oliveira** [comment]
Still can't find it, but at least I found an edge limitation I removed 👍
