### ISSUE TITLE
Have the action work on Windows builds (from setup-erlang)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#12]
At the moment it's Linux only.

**Comment by paulo-ferraz-oliveira** [comment]
We could, to start with, go with pre-built images (pretty much like those we have for Linux, from Hex.pm). We just need a repeatable way to list them, I guess.

**Comment by starbelly** [comment]
We definitely do. 

One problem I always have with supporting windows though, just to state it is, I don't have a machine that runs windows. I have used VMs in the past, but it is painful, even on the most powerful machines.  I'm stating this to be clear that from my end the amount of support I can give for windows will be limited. I've always said if windows users want windows support, they need to get involved.

Devoid of that, yes, we need windows support, this is something that the communities all around are lacking. gleam's setup erlang merely uses `windows-latest` as made available by gh actions. Further and to your point, we can just use the pre-built packages from erlang/otp. For elixir it would have to be installed using their web installer or chocolatey, which ever is easier, but these aren't in a list somewhere, I suppose they could be, but I don't have control over that in regards to bob, @ericmj would have to comment further.

**Comment by paulo-ferraz-oliveira** [comment]
> from my end the amount of support I can give for windows will be limited

Same here.

> if windows users want windows support, they need to get involved.

Agree, though we could initially try for bare minimums, I guess. I added CI/Windows in `lager` and was unable to test it locally before that, for example. (if it ever breaks though, that might be a problem, since it's the same CI element).

> gleam's setup erlang merely uses windows-latest as made available by gh actions

I'm not simply talking about the container. That's the easy part. I'm talking about the builds (which usually revolve around `choco` from what I've seen). 👍

**Comment by starbelly** [comment]
> Agree, though we could initially try for bare minimums, I guess. 

Yup, I agree 👍

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira Yeah, I'm thinking we do the bare min at this point: 

- users specifies windows-latest along with our action
- action runs a batch script in our repo which executes `choco install erlang`
- batch script also copies another batch script into place like the following for rebar3 docs: 
     ```
     @echo off
      setlocal
      set rebarscript=%~f0
     escript.exe "%rebarscript:.cmd=%" %*
    ```
- Now the user can do steps in their github workflow such as `rebar3.cmd ct` 

We would at least have some support for windows then vs none. 

Thoughts?

**Comment by starbelly** [comment]
Ok, per feedback I got from OTP team the windows builds made available on github should be good to go, which obviates choco. Specifically, there should be a flag we can pass to the installer for an unattended install.

**Comment by wojtekmach** [comment]
Yup, the flag is `/S`, see https://github.com/erlef/build-and-packaging-wg/issues/26#issuecomment-832205149 for more information.

**Comment by paulo-ferraz-oliveira** [comment]
Cool, that's what I was expecting. Have had no time for this, with all the SpawnFest stuff, but may find some soon, who knows. (if I actually used Windows, I would - otherwise this'll be a **learning and development** experience, for me).
