### ISSUE TITLE
Wrong Erlang/OTP version `maint-x` matched when requesting `x`

### ISSUE THREAD

**Issue by lukaszsamson** [erlef/setup-beam#120]
It seems that OTP 25 is built without `KERL_BUILD_DOCS=yes`
This breaks tests in [elixir_sense](https://github.com/elixir-lsp/elixir_sense/runs/6676822770?check_suite_focus=true)

**Comment by paulo-ferraz-oliveira** [comment]
Hello, @lukaszsamson.

This action imports pre-compiled Erlang/OTP builds from Hex.pm (e.g. https://repo.hex.pm/builds/otp/ubuntu-16.04/builds.txt), but I'm actually not sure they'd use `kerl` for compiling.

I'd ask @ericmj to pitch in, though, as something might've changed between 24 and 25 🤷 

Cheers.

**Comment by ericmj** [comment]
We are building the docs the same way we did for 24: https://github.com/hexpm/bob/blob/main/priv/scripts/otp/build_otp_ubuntu.sh#L38. Did something change?

**Comment by wojtekmach** [comment]
As far as I know nothing changed. The release contains doc chunks:

```
$ wget https://repo.hex.pm/builds/otp/ubuntu-20.04/OTP-25.0.tar.gz
$ tar xzfv OTP-25.0.tar.gz
$ ls OTP-25.0/lib/stdlib-4.0/doc/chunks/
```

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, even before checking it, this seems about right... You're asking for `25`, not `25.0`, so our algo. is serving you the highest available 25, which should be `maint`.

**Comment by ericmj** [comment]
> Yeah, even before checking it, this seems about right... You're asking for 25, not 25.0, so our algo. is serving you the highest available 25, which should be maint.

I don't think unreleased versions should be picked unless the user explicitly asks for it.

Since it seems to be common mistake to use floats in the versions maybe we should warn unless the version is a string?

**Comment by lukaszsamson** [comment]
> You're asking for `25`, not `25.0`, so our algo. is serving you the highest available 25, which should be `maint`.

Am I? Is it parsed as flat 25.0?

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I might have assumed, but:
1. if you use `25` (number, not string), this is picked up as 25
2. if you use `25.0` (number, not string), this is picked up as 25 (blame YAML, and the interpreter not me 😄)

Can you show me the bit of your GHA where you config. the versions?

(also, check https://github.com/erlef/setup-beam#usage, for more details on this)

**Comment by paulo-ferraz-oliveira** [comment]
> I don't think unreleased versions should be picked unless the user explicitly asks for it.

Agreed, but there is that element of "guessing" that the version choice algo. is using. If there's a rule for removing some versions (e.g. they'll always start with `maint-`) I guess we could remove those from the "guessing" but. I'm also trying to understand if this was never an issue because no one ever used "chunks"...

> Since it seems to be common mistake to use floats in the versions maybe we should warn unless the version is a string?

We could warn, but:
1. there's a flag to overcome this (guessing) limitation already,
2. there's a disclaimer in the README.

Warning would probably not be beneficial for all those users that've never had similar issues and for which the action is working as expected...

**Comment by paulo-ferraz-oliveira** [comment]
@lukaszsamson, we might have to fix something, although we also accept pull requests 😄 In any case, I'd have to review the algo. that picks the Erlang version properly.

**Comment by paulo-ferraz-oliveira** [comment]
@lukaszsamson, I'm trying to replicate this issue, but with no success. Can you tell me what version of the action you're using? It might have occurred in the past, but since we've supposedly fixed version-related issues. If I use '25' in a test, I get '25.0.2', not `maint-`. Thanks.

**Comment by lukaszsamson** [comment]
Yep, Now it's working correctly (https://github.com/elixir-lsp/elixir_sense/runs/6992540042?check_suite_focus=true), at least since 25.0.1. My guess is that OTP version isn't picked correctly if it is missing point release (as it was with 25.0).

I'm on v1 btw

**Comment by lukaszsamson** [comment]
The other thing is that maint build is missing doc chunks but this is not relevant here

**Comment by paulo-ferraz-oliveira** [comment]
Hm... we'd previously discussed that both 25 and 25.0 picked maint-25, but now something changed. I'd need to perform a few more tests to have something conclusive.

**Comment by paulo-ferraz-oliveira** [comment]
I see. I think I was able to replicate this. `25.0` is apparently not taken into account (as it's not semver) by the lib. we're using, so it skips to `maint-25`. Well, at least now I was able to replicate it (with your hint - which lead me to fake the downloaded `builds.txt` file).

**Comment by paulo-ferraz-oliveira** [comment]
I believe I've tracked this down and will pull request. At the same time, I'm taking @ericmj's suggestion into account and being more strict with `maint-` (meaning you should only be able to use them if in "strict version" mode, and not loosely).

@lukaszsamson, FWIW, we'd already had similar issues like these when 24.x came out, but there's only a small time window until they stop showing up (as you saw, once Erlang 25.0.1 was out).
