### ISSUE TITLE
Install specific non-latest patch OTP version

### ISSUE THREAD

**Issue by axelson** [erlef/setup-beam#123]
My understanding is that `24.3.4` is a specific OTP version. However it does not appear to be possible to install `24.3.4` via this action. Instead `24.3.4.2` is installed. Is there a way to specifically install `24.3.4`?

The reason that I want this is so I can be very specific about the Erlang version we're using in development, prod, and CI.

**Comment by paulo-ferraz-oliveira** [comment]
@axelson, did you try what I proposed on the previous message? Let me know. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this for lack of response. Feel free to re-open if the issue persists.
