### ISSUE TITLE
Support for Debug version of OTP

### ISSUE THREAD

**Issue by eric0fw** [erlef/setup-beam#128]
I have a use case where I would like to attach GDB to the BEAM to find out what is happening during boot-up. Can I get guidance on what I need to do here to include the debug symbols? I am happy to prepare a PR and document how to debug the BEAM from within k8s (I can already attach the etp GDB macros in k8s and even pause the process during boot using tini, I'm just missing debug symbols).

**Comment by paulo-ferraz-oliveira** [comment]
Hey.

I don't believe we'd mind adding the debug functionality (e.g. via an input option), but... this action doesn't create the Erlang, Elixir, Gleam, etc. builds, it just fetches them (pre-built). So unless all (or some of) the sources where we fetch the builds are Ok with providing a properly identified debug build (for which the configuration options would probably be hard-coded), it won't be possible for us action maintainers.

@ericmj, is it expected that Bob (or whatever system might replace it) eventually makes debug-enabled Erlang or Elixir builds available?

Cheers.

**Comment by eric0fw** [comment]
@ericmj I am more than happy to do the work. Just point me in the right direction.

**Comment by ericmj** [comment]
What's the need for debug builds in CI? It seems like something that's not often required. Could you do this outside of CI if it's only for debug purposes?

I am hesitant to increase the build matrix in Bob because we want to reduce the maintenance burden on it.

**Comment by eric0fw** [comment]
It is not used in CI. It's for when ERTS is embedded in the release.
We have a sandbox and staging environment working in k8s. The environment has hundreds of variables which had my fingers bleeding when I tried reproducing this locally. Furthermore, we see behaviour at startup that only misbehaves in k8s before the REPL can be used for debugging. So more visibility into what the VM is doing is critical.

**Comment by paulo-ferraz-oliveira** [comment]
> It's for when ERTS is embedded in the release

How are you using this action to embed ERTS in your release?

In any case, it seems you need something custom (and would allow you to tweak the compilation flags, at the same time), so I'd propose you look into https://www.erlang.org/docs/21/installation_guide/install, or a tool like https://github.com/kerl/kerl, which somewhat eases building+compilation but might not be as low-level as you require.

**Comment by paulo-ferraz-oliveira** [comment]
As per the previous interaction, and @ericmj's comments, it seems the action won't evolve in the expected path of the requester. Feel free to re-open if you feel there's a viable alternative we can explore. Cheers.

**Comment by ericmj** [comment]
@eric0fw If you are willing to contribute it to https://github.com/hexpm/bob we would merge it given it doesn't increase the maintenance too much.

**Comment by paulo-ferraz-oliveira** [comment]
👍 and, if after that, you want to contribute options to this GHA we can also discuss a path forward, "given it doesn't increase the maintenance too much."
