### ISSUE TITLE
Publish Action to Marketplace

### ISSUE THREAD

**Issue by tonnenpinguin** [erlef/setup-beam#129]
Hi all!
First, thanks for the fantastic work! :)

I was wondering if there was any way this action could be [published](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) to the Github Marketplace (ideally as a verified contributor).

My company only allows either verified actions or private forks and I imagine others are in the same boat.

Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
Hi.

I'm not sure what that would entail. @starbelly, are there plans to publish this on the Marketplace? Does anyone have experience with this? (or can we figure out an alternative, if we don't want this?)

> I imagine others are in the same boat.

It's possible, but we haven't had this type of request before. One of the blockers, though, might be the maintenance burden (if it exists or is a burden), because this is all voluntary work.

Cheers.

**Comment by tonnenpinguin** [comment]
The docs made it sound like it would only be one additional checkbox when creating releases after the initial setup has been performed. It does require the host organization to be verified and required 2FA if I understood correctly, so this might be a problem

**Comment by paulo-ferraz-oliveira** [comment]
Let me check if it's just that (the checkbox and 2FA), on the next release, and also have input from other maintainers. It might be doable/wanted.

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, is this something we want to do? I'm not sure we can create releases for the actions, but maybe not all are comfortable with requiring 2FA (?)

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, do you want to give this a look? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@tonnenpinguin, we're not doing GitHub Marketplace publish, at the moment, due to the 2FA element and the general lack of interest (this issue is a few months old but nobody else +1'd it)... Feel free to re-open if you want this discussion to continue. Thanks.

**Comment by tonnenpinguin** [comment]
Thanks for your efforts and the feedback!
We forked the repo and are working with the that for now, so if it's not an issue for others it's also ok for me :)
