### ISSUE TITLE
Add support for ubuntu-22.04 runners

### ISSUE THREAD

**Issue by aslilac** [erlef/setup-beam#130]
Currently fails to detect the OS and errors out

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @aslilac.

Are you using the latest version? Let me check this. I believe there was a PR (from me), but I don't know if we tagged the latest code recently.

Cheers.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, PR is here: https://github.com/erlef/setup-beam/pull/124. Let me just confirm something with the other PR that's open and then we can probably have a release soon. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Until the release I believe you can use `@main`, instead of  `@v1`. If you find issues you're more than welcome to report them to us.

**Comment by aslilac** [comment]
Oh, neat! Yeah I was just using the latest @v1, I’ll try main for now

**Comment by paulo-ferraz-oliveira** [comment]
> Oh, neat! Yeah I was just using the latest @v1, I’ll try main for now

Using `@vxy.yz` is the preferred method, for sure, especially for repeatability purposes (any change might introduce unexpected changes to your CI); `main` is last-resort...
