### ISSUE TITLE
Non-crash on invalid Elixir+OTP combo

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#131]
(initially reported by @tsloughter via Erlang Slack)

If we choose Elixir version 1.12 and Erlang version 25, the action (ran it today) will end up choosing Elixir 1.12.3 and Erlang 25.0.3. 

Because of a code validation, though, it'll not find `v1.12.3-otp-25` (from [builds.txt](https://repo.hex.pm/builds/elixir/builds.txt)) and will fall back to v1.12.3 (which is compiled with Erlang 22).

The question is: **does this validation actually make sense?** Or should we assume that if a combo is possible (for Elixir version+Erlang major) it'll always be found in `builds.txt` and that the fallback can be removed from our code?

Adding @ericmj @wojtekmach to recruit your help. Thanks much.

P.S.: the bit of code in question is this https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js#L200.

**Comment by wojtekmach** [comment]
If someone explicitly sets a given Elixir and a given OTP, and we cannot find it, I don't think there should be a fallback, I think we should error. Otherwise people might think they stuff works on a given combination and in reality we just don't know.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, `otp` is always compulsory, so I guess you're right and we should get rid of that fallback code...

**Comment by tsloughter** [comment]
It already does the fallback? Then why would it be using OTP-25 in my case if the combo doesn't eixst?

I also completely agree with @wojtekmach, there should be no fallback.

A nice feature would be the option to let the setup action figure out the matrices though. Like if I want to test Elixir 1.12 and 1.13 with all the Erlang's they support:

```
        otp_version: ['25.0.3', '24.1.2', '23.3.4.2']
        elixir_version: ['1.13.4', '1.12.3']
```

right now I'll have to manually add `include` directives I think, to keep it from failing.

Maybe nothing we can actually do in the action to modify the strategy, I'll go look in a bit to see if github allows that. 

Something like:

```
    strategy:
      all_supported_otps: true
      matrix:
        elixir_version: ['1.13.4', '1.12.3']
        os: [ubuntu-18.04]
```

**Comment by paulo-ferraz-oliveira** [comment]
> Then why would it be using OTP-25 in my case if the combo doesn't eixst?

It first chooses the OTP version (in your case, 25), then the Elixir version (it can't find a compatible `v1.12.3-otp-25`, so falls back to the non-OTP version `v1.12.3`, which is compiled for Erlang 22. You then get an error, instead of a crash (I'm PRing to fix this, though).

> A nice feature would be the option to let the setup action figure out the matrices though

It would be best to open a separate issue for this (maybe copy-pasting your text) so we handle the issue at hand first, and then the feature request.

>         otp_version: ['25.0.3', '24.1.2', '23.3.4.2']
>        elixir_version: ['1.13.4', '1.12.3']

From my PR on, if you do that, the action will crash when trying for 1.12.3 and 25.0.3.

**Comment by paulo-ferraz-oliveira** [comment]
Already failing as expected: https://github.com/erlef/setup-beam/runs/7949835939?check_suite_focus=true#step:5:17; in this case, Elixir 1.1.x / OTP-23.

**Comment by tsloughter** [comment]
Nice :+1:
