### ISSUE TITLE
Add support for .tool-versions files

### ISSUE THREAD

**Issue by kevinlang** [erlef/setup-beam#137]
Thank you for this excellent Github action!

Most of the time, I want the action to run the same environment that I use locally, which I specify with the asdf version manager that many others use for Elixir and Erlang. It would be convenient to just set the `version-file` key or something similar to `.tool-versions` and then have it automatically resolve the values from there. Setting this value would also necessarily set `version-type` to `strict` as well.

This can be done manually, probably, by wiring up another external action that does this reading, then passing along the values to this action. But Github actions are finicky enough that I think there is a benefit to having this functionality baked into this action.

This is a feature that is similar to what the `setup-node` action supports. 

https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file

**Comment by paulo-ferraz-oliveira** [comment]
For reference, the goal here is to:
1. have a new (optional) key that points to a file
2. have that file read and specify the tool versions for Erlang, Elixir, etc. (need to make sure what the correspondence is, here)
3. set `version-type` to `strict` forcefully

**Comment by paulo-ferraz-oliveira** [comment]
I started implementation on this. Just need to make sure I have a good wait to parse the file. I'll look at how `setup-node`'s doing it.

**Comment by starbelly** [comment]
How we do at work is with a composite action, I suspect that won't be great for our purposes. 

But FWIW: 

```
#!/bin/bash 

VER_FILE=".tool-versions"
ELIXIR_REGEX="^elixir (.*)"
ERLANG_REGEX="^erlang (.*)"
while read line
    do
       if [[ $line =~ $ELIXIR_REGEX ]];then 
           echo ::set-output name=elixir-version::"${BASH_REMATCH[1]}"
       fi

       if [[ $line =~ $ERLANG_REGEX ]]; then
           echo ::set-output name=otp-version::"${BASH_REMATCH[1]}"
       fi

    done < $VER_FILE
```

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, I believe I'll have to read the file from within JavaScript, since that's where I handle the inputs. I'll then generate some info./warnings based on that to make for easier consumption. I thank you for letting me know about your approach, though.

**Comment by paulo-ferraz-oliveira** [comment]
Took a while longer than I expected, but I believe I have a complete working solution in the linked pull request.

**Comment by yordis** [comment]
For future references to other ecosystem: https://github.com/straw-hat-team/github-actions-workflows/tree/master/asdf/get-version

I have been doing that for a while now if you are a user of `asdf` and need this type of thing.

**Comment by paulo-ferraz-oliveira** [comment]
I deleted a comment by mistake. In any case, it seemed unrelated to the request posted here and more of a generic comment on how stuff's done, **outside** `setup-beam`. It pointed to https://github.com/straw-hat-team/github-actions-workflows/tree/master/asdf/get-version.

**Comment by yordis** [comment]
Sorry, @paulo-ferraz-oliveira was trying to help the next person browsing the topic more than anything! (including people from outside Erlang ecosystem since I done searches before across GitHub to see if people solved the problem somehow)

My apologies for the inconvenience.

**Comment by paulo-ferraz-oliveira** [comment]
No inconvenience. In any case I was also thinking about this: how to make the solution to this problem more generic (yours seems to address a single variable; we'd usually need to address several variables), e.g. https://gist.github.com/paulo-ferraz-oliveira/61e243a67186788c56f8e8ee7bfdb6d3 - where the first code bit would be _the action_ and the second one a _generic way to use it_.

**Comment by yordis** [comment]
@paulo-ferraz-oliveira https://github.com/straw-hat-team/github-actions-workflows/pull/3 you can find an example here: https://github.com/straw-hat-team/github-actions-workflows/tree/master/asdf/get-versions

This should be generic enough and be able to read multiple versions at once. The tricky bit is that Github Actions Outputs can not be dynamic so you need to output a single value as JSON and parse in other Actions to get around the limitation.

At least I tried and didn't work, I hope I am wrong, but this works for now.

**Comment by paulo-ferraz-oliveira** [comment]
Hello again. I ended up cooking my own action (just released a few minutes ago): https://github.com/paulo-ferraz-oliveira/parse-tool-versions

Some notes:
1. works on all platforms (Windows, Ubuntu, MacOS) and all declared GitHub Actions' shells (I'm actively testing for all this in the action's CI workflows)
2. works with outputs (no JSON required), instead of environment variables (I wanted the latter, but it appears there's a GitHub security limitation on this) - while env. variables would be nicer to the eye, there's no big difference in typing `${{steps.tool-versions.outputs.ruby}}` instead of `${{env.TOOL_VERSIONS_ruby}}` (or whatever I'd end up deciding to name it)

**Comment by paulo-ferraz-oliveira** [comment]
Oh, and regarding a potential update to your action, you can use ` >> $GITHUB_OUTPUT`.

Look at my Gist where I do

```bash
echo "$VARNAME=${!VERSION}" >> "$GITHUB_ENV"`
```

It's dynamic and should work for outputs, e.g.

```bash
echo "$VARNAME=${!VERSION}" >> "$GITHUB_OUTPUT"
```

**Comment by yordis** [comment]
> It's dynamic and should work for outputs, e.g.

I tried that and didn't work, at least not in the reusable Action. Maybe I did something wrong 🤷🏻

**Comment by paulo-ferraz-oliveira** [comment]
> I tried that and didn't work, at least not in the reusable Action. Maybe I did something wrong 🤷🏻

You can also [check above](https://github.com/erlef/setup-beam/issues/137#issuecomment-1287939479) how @starbelly's doing it, and it's working!

**Comment by yordis** [comment]
> echo ::set-output name=elixir-version::"${BASH_REMATCH[1]}"

Notice that the name is static, and also, you would need to configure the `outputs` of a job https://github.com/straw-hat-team/github-actions-workflows/blob/1d5dfecb57a36a4cda721dd9f85ff2dff8b2fd64/asdf/get-versions/action.yml#L11-L14

Otherwise it wouldn't have anything in it 😢

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I see the difference now, yeah.

@starbelly's case would work since it's not an action, but a script run within the steps (if I had to guess). Your case is more complex, and yes, if you want to declare the outputs you probably need to make sure they're not dynamic.

[My action doesn't declare outputs](https://github.com/paulo-ferraz-oliveira/parse-tool-versions/blob/main/action.yml), so maybe that's an important difference.

**Comment by paulo-ferraz-oliveira** [comment]
For [JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions) "if you don't declare an output in your action metadata file, you can still set outputs and use them in a workflow."

There's no such similar note for composite actions, though.

**Comment by yordis** [comment]
> [My action doesn't declare outputs](https://github.com/paulo-ferraz-oliveira/parse-tool-versions/blob/main/action.yml), so maybe that's an important difference.

Did that one work? If so, I can port into it and use JS, then! Worth it just for that!

**Comment by paulo-ferraz-oliveira** [comment]
> Did that one work?

Not declaring outputs? Or the dynamic stuff?

Both worked: 😄

- [action.yml](https://github.com/paulo-ferraz-oliveira/parse-tool-versions/blob/main/action.yml) has no declared outputs
- [accessing different outputs](https://github.com/paulo-ferraz-oliveira/parse-tool-versions/actions/runs/3560319985/workflow#L22) is easy from just [this simple declaration](https://github.com/paulo-ferraz-oliveira/parse-tool-versions/actions/runs/3560319985/workflow#L16)

Yeah, I went with JavaScript, initially, just for wanting to have cross-platform execution made easy. Then I remembered environment variables couldn't be set between steps (not using JS, at least) and scoped it to outputs.
