### ISSUE TITLE
Matchers (from setup-erlang)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#14]
From Bryan's comment: https://github.com/erlef/setup-erlang/pull/1#issue-592264162.
"There are no matchers yet, it isn't clear what we want/need yet."

I'm opening this issue so that:
1. pull request erlef/setup-elixir#9 doesn't get overwhelmed,
2. it can be dealt with later, except if it's important to be in the first version.

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, I've been reading into matchers.

I'm not sure:
1. we need/want some,
2. this won't be a never ending task, since logs may change from version to version and we'd have to keep adapting.

What do you say we close this?

**Comment by starbelly** [comment]
I think they are a nice-to-have but I don't seem that as critical. Quite ok with closing for now. I suspect someone will want this and if they do, they can re-open this or open a PR IMO.
