### ISSUE TITLE
Support versions of Gleam at or older than v0.22.1 on Windows

### ISSUE THREAD

**Issue by lpil** [erlef/setup-beam#140]
The format used for Gleam binary archives changed after v0.22.1. The Linux installer supports both formats, but the Windows one only supports the new format.

Port the Linux code to Windows so both are supported.

More context can be found here: https://github.com/erlef/setup-beam/pull/138

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, I pull requested for this (mostly because I wanted to have fun with Windows scripting). If you wanna check if out, it's linked in the Development section, to the right.

**Comment by lpil** [comment]
Brilliant, thank you!
