### ISSUE TITLE
Have rebar3 + rebar3.cmd work on a Windows CMD shell

### ISSUE THREAD

**Issue by lpil** [erlef/setup-beam#147]
Hello!

The rebar3 documentation recommends creation of a `rebar3.cmd` file so that rebar3 can be run from the shell.

https://rebar3.readme.io/docs/getting-started

> copy rebar3 file to %USERPROFILE%\bin
> make a file using notepad.exe with the contents of the .cmd invoker for escript to run rebar3 (provided in this document below)
> open a new command-line and type rebar3

```batch
@echo off
escript.exe "%~dpn0" %*
```

setup-beam doesn't do this which I believe results in Gleam's Windows workflows to fail when it attempts to call rebar3.

Could we also create this file?

Thanks,
Louis

**Comment by paulo-ferraz-oliveira** [comment]
Hey, Louis.

Let me check that for you real quick...

...

We do create a `.ps1` though; is it possible for Gleam to use that one, on Windows? (or maybe we can create a copy of that one in `.cmd` format)?

**Comment by paulo-ferraz-oliveira** [comment]
For ref.: https://github.com/erlef/setup-beam/actions/runs/3226773628/jobs/5280715405#step:3:25
(that's `rebar3` in a Windows environment)

**Comment by lpil** [comment]
Perhaps that could work!

The rebar3 docs say to create a `.cmd`, so on Windows we've been excuting `rebar3.cmd`. `rebar3` alone doesn't work with the official installation methods outside of a shell. We do the same for Elixir with `elixir.bat`.

https://github.com/gleam-lang/gleam/blob/80fc41a0fa92061a79806aafe7e1a6ce5b15da36/compiler-core/src/build/project_compiler.rs#L27-L32

Is there a way on Windows to use whichever of `.ps1` and `.cmd` is avaliable? If not it would be great to have `.cmd` as that's what the rebar3 team document.

**Comment by paulo-ferraz-oliveira** [comment]
> Is there a way on Windows to use whichever of .ps1 and .cmd is avaliable?

I'm not really sure, sorry. (and I do agree that stuff should be consistent with other sources - as per your comment on `rebar3`). I just did the bare minimum, in the past, to have the action work on the Windows containers. In any case, we could also check with `rebar3` (@tsloughter, @ferd) if that approach is still the "default" one or if they have something else they could propose.

No time right now, but I could check this later to see if there's a way to "on Windows to use whichever of `.ps1` and `.cmd` is avaliable?" as you suggest.

**Comment by paulo-ferraz-oliveira** [comment]
Nice, thanks, @ferd. TIL. @lpil, maybe the reference you saw where "The rebar3 docs say to create a .cmd" can be tweaked/updated? I'm not sure we need to pursue this further, but I'm willing to help if you believe it's required for us to expose something in the action. I forgot to ask this: what's failing? Do you have like a minimal example I can look at? Thanks.

**Comment by lpil** [comment]
If I attempt to exec `"rebar3"` from a program rather than from a Windows shell it'll fail due to the program not being found. Instead I have to use `"rebar3.cmd"` as documented. The same for `"elixir"` and its `"elixir.bat"`.

I can't switch over to `"rebar3.ps1"` because it commonly isn't present. All installation methods I've come across create `rebar.cmd` except `setup-beam`, while not all create `rebar.ps1`.

**Comment by paulo-ferraz-oliveira** [comment]
I don't mind creating and packaging `rebar3.cmd` if it's needed. I just wanna make sure we have a solution that's maintainable. The last time I saw `rebar3.cmd` is was a one liner (two lines, actually), but I may remember incorrectly. Do you have a reference that we could implement? I believe we need that file and adding it to the path, then a couple of tests and... done! Thanks.

**Comment by ferd** [comment]
The implementations at https://github.com/erlang/rebar3/blob/feb4a9115644fd74b3e4dc12f4a85c8a9daf25ef/apps/rebar/src/rebar_prv_escriptize.erl#L327-L339 are those we use internally and have never needed to really adjust much

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, @ferd. Come to think of it, that's probably where I got inspiration for https://github.com/erlef/setup-beam/blob/main/src/install-rebar3.ps1#L24 in the first place. `.cmd` should be feasible then...

**Comment by lpil** [comment]
Wonderful, thank you both!

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, let me know if this is Ok/enough for you (I'll also open a pull request here): https://github.com/paulo-ferraz-oliveira/my_gleam_ci_test/actions/runs/3300485684/jobs/5445030270.

You can see I'm running [`rebar3`](https://github.com/paulo-ferraz-oliveira/my_gleam_ci_test/actions/runs/3300485684/jobs/5445030270#step:4:2) and [`rebar3.cmd`](https://github.com/paulo-ferraz-oliveira/my_gleam_ci_test/actions/runs/3300485684/jobs/5445030270#step:5:2) (no path) in a `cmd` shell.
