### ISSUE TITLE
Bad version results in confusing error message

### ISSUE THREAD

**Issue by tsloughter** [erlef/setup-beam#15]
I accidentally tried to use an Elixir version that doesn't exist, `elixir-version: 11.1.1`, and the error message given is "Error: Cannot read property 'includes' of undefined" instead of saying the Elixir version does not exist.

**Comment by starbelly** [comment]
Agreed and seems like we need to check for this here : https://github.com/erlef/setup-elixir/blob/885971a72ed1f9240973bd92ab57af8c1aa68f24/src/setup-elixir.js#L78

**Comment by starbelly** [comment]
Example : https://github.com/starbelly/tristan_regression/runs/2161573116?check_suite_focus=true

**Comment by paulo-ferraz-oliveira** [comment]
I'm updating #9 to have better output in case of errors. Takes a while, since I need to add tests to the stuff I'm doing.
