### ISSUE TITLE
The `set-output` and `save-state`command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by eddy147** [erlef/setup-beam#154]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It will be disabled from 23rd March 2023

**Comment by eddy147** [comment]
Already handled in https://github.com/erlef/setup-beam/pull/148

**Comment by paulo-ferraz-oliveira** [comment]
Yes, this should be in v1.14, already. If you're using v.13, or v.13.x you won't have it, though. Thanks.
