### ISSUE TITLE
Strange build issues on GHA

### ISSUE THREAD

**Issue by lucacorti** [erlef/setup-beam#155]
Hi,

Builds for a number of projects I have on github using setup-beam started failing suddenly in a very consistent way despite I made no changes to them. This is an example:

https://github.com/lucacorti/jsonapi_plug/actions/runs/3460577293/jobs/5777255548

It's interesting they are only failing in the test step (matrix based with multiple versions), while the lint step (matrix with only one combination) seems to work fine.

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @lucacorti.

We fetch our version lists from here (e.g. for Ubuntu 22.04): https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt.

One of the errors you show

```
Requested Erlang/OTP version (23) not found in version list (should you be using option 'version-type': 'strict'?)
```

is indeed correct according to that list and this [action's README](https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp).

You seem to be targeting `ubuntu-latest` which might have changed recently, thus causing that issue (I will validate soon). With that strategy this might happen again in the future given `-latest` will always be a running target.

**Comment by lucacorti** [comment]
Oh I see, that makes sense indeed. I'll try setting 20.04 as the target.

Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
[GitHub Actions: Ubuntu-latest workflows will use Ubuntu-22.04](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) was five days ago (November 9, 2022). Does this coincide with your "failing suddenly"? If it does, feel free to close the issue, or keep it open if you want to discuss something further.

**Comment by lucacorti** [comment]
Yes, that's it. I failed to notice the OS comaptibility bit. Thanks!
