### ISSUE TITLE
Install Slack integration

### ISSUE THREAD

**Issue by efencee** [erlef/setup-beam#160]
Hello,

Slack requires repo owners to install the Slack integration to a repository. If installed, this integration will enable my team to keep up with updates on the repo.

Can you install the integration, so we can subscribe to repo updates on Slack?

Thank you,
Favour

**Comment by starbelly** [comment]
Sorry, I'm not sure what you're talking about or why you would need to us to install anything anywhere. Closing this, but if you feel this was in error and you have an issue relevant to this action, please re-open and explain in detail.

**Comment by efencee** [comment]
Hello Bryan, I'm sorry about the initial lack of clarity.

My team is interested in this receiving notifications on updates to your repository. We would like to automate the process, so we can receive Slack notifications when an event we are interested in occurs in the repository. To achieve this, we tried subscribing to the repo using the GitHub to Slack integration. However, we were unable to complete the process as the Slack integration needs to be installed on the repository by the repo owner before we can subscribe.

Could you install the Slack integration to the repository? Doing so will enable us to successfully subscribe to receiving updates on your repository via Slack.

Thanks,
Favour

**Comment by starbelly** [comment]
I see what you mean, sorry if I was rash. I don't know what the security implications of this are.

**Comment by paulo-ferraz-oliveira** [comment]
I believe it's possible you (or members of your team) subscribe to the releases, as seen here
<img width="318" alt="image" src="https://user-images.githubusercontent.com/7303768/203647654-46acc128-ffc4-48ac-b14b-7d740cde702c.png">

Like @starbelly, I'm not sure of the security implications of your request, but it does seem (as he points out) the bot was made to be used for repositories you own.

**Comment by yordis** [comment]
Subscribing to release or using tools like dependabot or renovate would help here as far as I can tell.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this, as it seems we'll not be doing it.
