### ISSUE TITLE
OTP Version not found (Elixir 1.11.0, OTP 23.1.1)

### ISSUE THREAD

**Issue by Samkeer1** [erlef/setup-beam#161]
It appears that recent updates to setup-beam have coincided with a new, unfamiliar error.

Config:
<img width="371" alt="Screen Shot 2022-12-02 at 11 38 37 AM" src="https://user-images.githubusercontent.com/43652523/205363181-488c7cad-3c4e-4bfd-9048-fb95797b07c5.png">
Error:
<img width="945" alt="Screen Shot 2022-12-02 at 1 35 04 PM" src="https://user-images.githubusercontent.com/43652523/205381178-cddb705e-0542-43e5-b738-e083a84e4a3d.png">

Following the error's guidance, I added strict version checking to my config:
Config change:
<img width="221" alt="Screen Shot 2022-12-02 at 1 38 41 PM" src="https://user-images.githubusercontent.com/43652523/205381653-8be09da4-8809-441d-9579-ff65a9e0b321.png">

Second error, when specifying strict version checking:
<img width="869" alt="Screen Shot 2022-12-02 at 1 34 16 PM" src="https://user-images.githubusercontent.com/43652523/205381091-74069f26-fe51-42af-94c3-3afd4e760893.png">

The second error looks familiar; noticed a [similar past issue](https://github.com/erlef/setup-beam/issues/56), but none of the solutions described there solved the problem or changed the error displayed.

I've tried a handful of different configurations and the two pictured errors are all I'm able to produce.

**Comment by paulo-ferraz-oliveira** [comment]
OTP 23 is not available for `ubuntu-latest` (was 20.04, recently moved to 22.04). If you take your previous action version (without all the changes you mention) and just move to `ubuntu-20.04` your problem should go away. Mind you, the action does not maintain the Ubuntu/OTP relation, though it uses it. This is maintained by the fine folks at Hex.pm, via https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt.

Closing. Feel free to re-open if the proposed solution does not work for you.

**Comment by halostatue** [comment]
I recently hit this error and it took a while to figure it out. I think that the idea of an OS/OTP version compatibility table as sort of suggested by #18 would be a *good idea* to add to the README, since this isn’t something that’s easily discoverable without digging into https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt vs https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt and seeing that `ubuntu-latest` changed from `ubuntu-20.04` to `ubuntu-22.04`.

**Comment by paulo-ferraz-oliveira** [comment]
I believe that [that list](https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp) exists in the README, so I'm confused as to what's being asked.

**Comment by halostatue** [comment]
So it does. Not sure how I missed it. Sorry.
