### ISSUE TITLE
Test "gleam check" (without OTP) failing

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#165]
Check https://github.com/erlef/setup-beam/actions/runs/3671327560/jobs/6206457051#step:11:11.

It started happening when `ubuntu-latest` moved from 20.04 to 22.04; check [this - 20.04 -](https://github.com/erlef/setup-beam/actions/runs/3528841440/jobs/5919348448#step:1:4) out (not failing).

I'm not sure if `gleam check` is supposed to run without Erlang/OTP, but the reason it didn't fail before was because both Ubuntu [20.04](https://github.com/actions/runner-images/blob/ubuntu20/20221027.1/images/linux/Ubuntu2004-Readme.md) and [18.04](https://github.com/actions/runner-images/blob/ubuntu18/20221018.2/images/linux/Ubuntu1804-Readme.md), as bundled by GitHub, for the actions, include Erlang/OTP (at the moment, 25.0.4) which will include `escript` which will prevent the action from failing in those versions.

The failing test was potentially written without that in mind.

**Comment by paulo-ferraz-oliveira** [comment]
I installed Gleam 0.23.0-rc1 in a Ubuntu 22.04 vanilla container (thus no Erlang) and running `gleam check` on `test-projects/gleam_gleam` fails with ```
Downloading packages
 Downloaded 2 packages in 0.11s
  Compiling gleam_stdlib
error: Program not found

The program `escript` was not found. Is it installed?
Documentation for installing Erlang can be viewed here:
https://gleam.run/getting-started/
```

so I'm kinda convinced OTP is required for the check. I'm gonna go with `gleam format` for that specific (failing) test.

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, if possible, could you confirm that `gleam check` requires OTP while `gleam format` does not? Does [our change](https://github.com/erlef/setup-beam/pull/164/files#diff-6640e8c668a6deeb426558faaa2b0f535d95814c09a05c044a1df27a008dd544R185) to the non-OTP test make sense? Thank you.

**Comment by lpil** [comment]
Neither `gleam check` or `gleam format` require OTP, so no, the change does not make sense to me.

**Comment by lpil** [comment]
`gleam check` _sometimes_ requires OTP. It depends upon the dependencies and the target being used. Using format makes sense to me! Thanks
