### ISSUE TITLE
Frequent failures when HTTP-calling GitHub

### ISSUE THREAD

**Issue by lpil** [erlef/setup-beam#167]
Hello! This month I've started to get CI failures very frequently when the action makes requests to the github API with `erlef/setup-beam@v1.15.0`

```
Error: Got 403 from https://api.github.com/repos/erlang/rebar3/releases?per_page=100&page=2. Exiting with error
```

https://github.com/gleam-lang/gleam/actions/runs/3725950844/jobs/6319069926

https://github.com/gleam-lang/gleam/actions/runs/3726000010/jobs/6319157464

https://github.com/gleam-lang/gleam/actions/runs/3726020768/jobs/6319192244

It is a transient error, if the workflow is retried it succeeds. I'm unsure what the cause is.

**Comment by paulo-ferraz-oliveira** [comment]
I'm also unsure what the cause is (I saw this happen once or twice during testing for a previous version), but it does seem transient, yes. I'm kinda thinking that we might be making too many requests (in a given time frame) to api.github.com, but the only way (as a quick win) I can see to fix this, for the time being, would be to have either an active sleep before that, or keep retrying until we do get those pages. Would you be Ok to test a potential fix to this I might do on a pull request?

**Comment by lpil** [comment]
Sure thing!

Perhaps we could apply a sleep and retry if it fails once? To avoid the performance hit. I also wonder if the response body will have more info too.

**Comment by paulo-ferraz-oliveira** [comment]
> Perhaps we could apply a sleep and retry if it fails once

That's what I was going for, mostly.

**Comment by paulo-ferraz-oliveira** [comment]
It's possible this is related to OS, but unlikely. I'm working on the fix at this very moment.

**Comment by kivra-fabber** [comment]
I'd be happy to test this. We have seen it quite a bit lately.

I haven't used a fork+branch for a GitHub Action before, would I configure it as such:

```
    - uses: paulo-ferraz-oliveira/setup-beam@too-many-requests-to-github
```

or do you need a release or tag for reference?

Side note: IIRC there is another unhandled HTTP error in this action that happens more rarely, when the installer downloads OTP with wget: https://github.com/erlef/setup-beam/blob/main/src/install-otp.sh#L13. It intermittently gets some bad status back from Cloudflare I think, but I'll do some more testing before creating an issue.

**Comment by paulo-ferraz-oliveira** [comment]
Thank you, @kivra-fabber. Let me know how it goes. If that doesn't work I'll need to dig deeper (and maybe you can show me some output). In any case, my pull request is basically done: I just need to understand why `git diff --exit-code` is stating a difference for no apparent reason...

Oh, it is no longer, after I added `--ignore-space-at-eol`. Strange, but mostly hopefully irrelevant stuff, in our context.

**Comment by fabjan** [comment]
I'm (kivra-fabber is my alter ego) on vacation now so won't be looking at job stuff until after New Years, but if nobody else has tested much and shared feedback here I will then.

**Comment by starbelly** [comment]
You should be able to dump the response (and headers) to ensure it is a rate limit exceeded exception. According to github docs, a 403 will be returned if the rate limit is exceeded. There's not a lot we can do sans putting the information we want to get from github somewhere else to circumvent the problem, or we could cache, that doesn't sound great to me. 

FWIW : 

> When using GITHUB_TOKEN , the rate limit is 1,000 requests per hour per repository. For requests to resources that belong to an enterprise account on GitHub.com, GitHub Enterprise Cloud's rate limit applies, and the limit is 15,000 requests per hour per repository.

**Comment by starbelly** [comment]
Update, I actually hit this, and can hit it pretty consistently and I don't think this is going to be because of rate limiting, not in the way I thought it would be happening anyway.

**Comment by lpil** [comment]
It's happening about 90% of the time for Gleam now. Let me know if there's anything you'd like me to add to Gleam's workflow that would help you debug.

**Comment by starbelly** [comment]
@lpil Is this happening to you only on pull requests?

**Comment by lpil** [comment]
No, it also happens on the main branch

https://github.com/gleam-lang/gleam/actions

**Comment by starbelly** [comment]
Hmm yeah : 

```
##[debug]{"message":"API rate limit exceeded for 13.88.61.32. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by lpil** [comment]
Option 4 sounds fab, especially alongside one of the other options for less precise version specifications.

**Comment by starbelly** [comment]
> Option 4 sounds fab, especially alongside one of the other options for less precise version specifications.

Yeah, that makes sense. Caching is inevitable whether it's done as part of the action or we lean on another resource. 

Here's a patched branch that won't hit the api if using version strict : starbelly/setup-beam@do-not-hit-api-when-strict

Result : https://github.com/starbelly/gleam/actions/runs/3772580173/jobs/6413594202

Seems fine, not sure about some of the windows failures though.

**Comment by lpil** [comment]
Could it apply when the version for Gleam and Elixir have 3 sections? They're using semver so it is possible to tell that the lookup isn't required in that case.

**Comment by starbelly** [comment]
That makes sense to me. We can do the same with rebar3 too. >= 3 parts constitutes an exact version. 

I also pondered on bundling data with the action. We could set something up that checks a few times a day and does a PR, force pushes to @v1, etc. I don't like caching (in any shape or form), but ... 🤔

**Comment by paulo-ferraz-oliveira** [comment]
> It's happening about 90% of the time for Gleam now.

Using the branch I cooked for testing?

**Comment by paulo-ferraz-oliveira** [comment]
> We'll need to re-think

1. there was a PR for this recently, but the caching portion of it got removed (and the PR is still up)
2. supposedly even pulling from Hex.pm was causing an issue, which is why the PR was created to start with
3. I don't know about authenticated requests either; used a bit of time to read some stuff but couldn't easily find the information and decided not to dig deeper

I believe the `strict` portion of the conversation would only solve part of the problems, but we could add that to my PR, sure.

> >= 3 parts constitutes an exact version.

How so? You mean >= x.y.z?
I'd prefer, if we go with something around strict, to go directly to the source to get the builds instead of touching the semver algo.

**Comment by lpil** [comment]
> Using the branch I cooked for testing?

Ah! I did not see the new version, I shall test that

> How so? You mean >= x.y.z?

If Gleam, rebar3, or Elixir have a version with 3 or more components then we know that it is an exact version and as such we don't need to query GitHub for the versions available.

I think using `strict` would not be a good solution because either the action would not work without it (making it mandatory), or a second solution would be needed for when it is present (making the `strict` specific solution redundant).

**Comment by paulo-ferraz-oliveira** [comment]
> If Gleam, rebar3, or Elixir have a version with 3 or more components then we know that it is an exact version and as such we don't need to query GitHub for the versions available.

Got it, but, in any case, I would propose not assuming this. If a consumer wants the input version to be strict they may indicate it via the appropriate flag. (whether or not the existence of this flag indicates that we don't use the GitHub API is probably discussible, but mostly I'd say this is an implementation detail).

> I think using `strict` would not be a good solution

At this moment we only query the GitHub API to fetch the versions so we can semver-compare them to the output and choose the appropriate one. If we were to use `strict` we could bypass this, so we'd have much less requests to the API, right? Or... I'm not getting what you're saying exactly 😄

**Comment by paulo-ferraz-oliveira** [comment]
> https://github.com/gleam-lang/gleam/actions/runs/3781281327/jobs/6428048215

I saw this (or similar, rather) during my tests implementing #168. The GitHub API response is not a JSON (which we're assuming) so the parse fails (this is most surely a 403 either for "lack of authentication" or "too many requests").

**Comment by lpil** [comment]
> If we were to use strict we could bypass this, so we'd have much less requests to the API, right? Or... I'm not getting what you're saying exactly 😄

Sorry, I mean that if we have a solution for this problem that only works if `strict: true` is set then we would need another solution for when `strict` is false or unset.

**Comment by starbelly** [comment]
> Sorry, I mean that if we have a solution for this problem that only works if `strict: true` is set then we would need another solution for when `strict` is false or unset.

Precisely. I'll get a PR up today for this. To be clear, we'll still need caching and retries. The action toolkit provides utility libs for doing all this. 

Related : 

- https://github.com/actions/toolkit/tree/main/packages/tool-cache
- https://github.com/actions/toolkit/tree/main/packages/cache

**Comment by kivra-fabber** [comment]
@paulo-ferraz-oliveira Alright I'm back. here are our results from one repository where we tested your patched setup-beam action:

On December 20 we had 25 failed pipeline runs due to 403 from the GitHub API in setup-beam. I patched our CI to use your branch that day and since then I can see at least 60 pipeline runs that were successful. I only saw one pipeline fail and that was from a branch that did not use the patched setup-beam.

I am just guessing here, but I'm fairly certain the GITHUB_TOKEN was the important part of the fix, and not the retries.

**Comment by starbelly** [comment]
@kivra-fabber  That makes sense in that you'll get a taller ceiling before hitting the limit if you're authenticated. 

This suggests to me that PRs for retrying and using GITHUB_TOKEN should be seperate. 

Here is another PR to avoid hitting the api if an exact version is provided (or in the case of OTP if the strict option is provided). 

https://github.com/starbelly/setup-beam/tree/do-not-hit-api-when-strict

@lpil  Would you mind testing this?

**Comment by lpil** [comment]
Hello! I've tested it with a few builds but it fails for OTP. The project does not use `strict: true`.

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, did you test the #168 branch?

**Comment by samaaron** [comment]
Hi, I'm currently getting this error:

```
Run erlef/setup-beam@v1
Error: Got 403 from https://api.github.com/repos/erlang/otp/releases?per_page=100&page=2. Exiting with error
```

Interestingly, it's only on Windows. Our Linux and macOS workflows are working just fine:

https://github.com/sonic-pi-net/sonic-pi/actions/runs/3855130607/jobs/6569863292

Is there an explicit change to my `yml` file I can make to specifically try #168 or should it just automatically use that now it's released? Also, I'm not doing anything explicit with tokens. Perhaps I should?

**Comment by starbelly** [comment]
Hi @samaaron  We're about to do a release where we default to `github.token` which I think should fix the problem. I'm about to merge this, could you test main after I do before we release it?

**Comment by fabjan** [comment]
> Also, I'm not doing anything explicit with tokens. Perhaps I should?

The action will use GITHUB_TOKEN from its environment if available. You can set it in your yml, where you use the setup-beam action:

```
      - uses: erlef/setup-beam@v1.15.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
```

**Comment by starbelly** [comment]
@fabjan  Correct, but also when #173 is merged, this won't be needed :) And to be clear, we won't support `GITHUB_TOKEN` passed via env anymore.

**Comment by fabjan** [comment]
@starbelly dangit, you responded too quickly for my useless reply to pass unnoticed!

If anyone reads that later and is confused, I deleted a comment that was made too quickly: I didn't know #172 existed, so I gave outdated advice. As I saved it, starbelly's simultaneous comment appeared and I realized my error.

**Comment by starbelly** [comment]
> @starbelly dangit, you responded too quickly for my useless reply to pass unnoticed!
> 
> If anyone reads that later and is confused, I deleted a comment that was made too quickly: I didn't know #172 existed, so I gave outdated advice. As I saved it, starbelly's simultaneous comment appeared and I realized my error.

No worries! I appreciate it and it wasn't wrong either! ❤️

**Comment by samaaron** [comment]
@starbelly - thanks so much for the response and for looking into this.

I just re-ran the failing Windows runs and one passed, but the other still failed with a similar error. I'm re-running it again now.

**Comment by starbelly** [comment]
FWIW I tested my fork of gleam against main : https://github.com/starbelly/gleam/actions/runs/3856710531

Looks good, the only failures are not related to this action.

**Comment by samaaron** [comment]
Things are looking good now. Perhaps it took a bit of time to propagate the update - maybe due to existing caches.

Thanks so much!

**Comment by warmwaffles** [comment]
I am also running into issues with this and look forward to a fix for the windows variants. On our existing pipelines, will we need to start providing a github token or should it "just work"?

**Comment by starbelly** [comment]
@samaaron  Great! I'll do a release shortly ❤️ 

@warmwaffles  No need to specify tokens with the last merge, it will "just work" ™️  👍

**Comment by starbelly** [comment]
v1.15.2  published and `@v1` updated. Thanks everyone!

**Comment by lpil** [comment]
Brilliant! Thank you!
