### ISSUE TITLE
Unit tests can fail with 403 (rate limit exceeded)

### ISSUE THREAD

**Issue by starbelly** [erlef/setup-beam#173]
This problem doesn't effect users of this action, rather they are workflows or part of a workflow that doesn't use our action, and thus do not authenticate with the github REST api. 

Resolution : Find simple and safe way to authenticate with github rest api for npm unit tests.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, we can go with just passing a token in, if that solves it.
