### ISSUE TITLE
Regression: Valid OTP Version is not found

### ISSUE THREAD

**Issue by maennchen** [erlef/setup-beam#175]
For Erlang 23.3, I get the following error.

```
Run erlef/setup-beam@v1
  with:
    otp-version: 23.2
    elixir-version: 1.11
    github-token: ***
    install-hex: true
    install-rebar: true
    version-type: loose
    disable_problem_matchers: false
Error: Requested Erlang/OTP version (23.3) not found in version list (should you be using option 'version-type': 'strict'?)
```

https://github.com/elixir-gettext/expo/actions/runs/3872550709/jobs/6601521921

This used to work back in November: https://github.com/elixir-gettext/expo/actions/runs/3457012505/jobs/5776830927

The version 23.3 is on the Hex.pm Bob List which I believe is the base for this action: https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt

**Comment by svrdlans** [comment]
Having the same issue, it stopped working a month ago.
The ubuntu version is 22.04 and erlang is 23.2. Screenshot attached.
![Screen Shot 2023-01-10 at 11 35 33](https://user-images.githubusercontent.com/5398719/211528939-91cfe2de-0b06-461f-877a-ee356d2728f8.png)

**Comment by maennchen** [comment]
@svrdlans Oh, you're right 😅

My bad, closing issue.
