### ISSUE TITLE
Add retries to HTTP calls (prevent 502?)

### ISSUE THREAD

**Issue by lpil** [erlef/setup-beam#178]
Hello!

I'm still getting errors from this action once or twice a day, for example when [GitHub's API returns 502](https://github.com/gleam-lang/gleam/actions/runs/3901504248/jobs/6663429913).

As these are transient errors it would save me time and annoyance waiting and manually rerunning jobs if this library defaulted to waiting a short period and then retrying any failed HTTP requests, rather than failing the job entirely at first occurrence. 🙏 

Thanks,
Louis

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @lpil.

We were doing this at some point in time, during the recent fixes, but decided to move to a smaller scope we could have data/results on.

It seems our recent fixes might have fixed some of your issues, but not all.

Care to try out @starbelly's https://github.com/erlef/setup-beam/pull/169 (though it might not be exactly what you require) and let us know how that goes?

Thanks much.

**Comment by lpil** [comment]
Will do!

**Comment by starbelly** [comment]
While I think retries is a thing to have, maybe caching as discussed in another issue is the thing to do here? 

https://github.com/actions/toolkit/tree/main/packages/tool-cache

^ specifically made for this purpose.

**Comment by starbelly** [comment]
A good suggestion was made in B&P meeting yesterday : Let's just put csv files up on a github page. After thinking about this we can just have a scheduled ci job that pulls the info, every N minutes, generates a csv based on results for rebar3 and gleam and does a pull request if needed (maybe checks to see if there's even a diff), pull request triggers a build of a github page, etc. There's an assumption in here that a github page will let us serve up a csv or json doc. 

Jose also stated we should just be able to use the builds file on repo.hex.pm for windows, is there a reason we hit github api for otp when it's windows right now and don't use builds csv?

**Comment by paulo-ferraz-oliveira** [comment]
It feels we'll be unfortunately doing something that GitHub should do itself. If we can hit the pages API why not this API? 😢 

On the other note, I can't remember why I chose the GitHub API, but I think it had something to do with our versions were managed (either not all releases had Windows, or Hex.pm builds.txt was not available, or something else, I can't quite pinpoint it).

I'm Ok with the suggestion, even if it means we're just avoiding one API to go to another one. 😄

**Comment by starbelly** [comment]
> It feels we'll be unfortunately doing something that GitHub should do itself. If we can hit the pages API why not this API?

I mean, I don't disagree, but I'm not sure we're going to be able to convince github to relax it's rate limit policy just for us :) I believe the idea here is that if we serve up a file vs github pages the limitation just goes away as there would be CDNs in the mix. This wouldn't be too different from caching in the action I suppose, but the complexity is also shoved off on to the cdn, and we can also update the content separately from the action which sounds good to me. If it makes a problem disappear and keeps the action simple, I'm all for it. 





> On the other note, I can't remember why I chose the GitHub API, but I think it had something to do with our versions were managed (either not all releases had Windows, or Hex.pm builds.txt was not available, or something else, I can't quite pinpoint it).

I seem to remember something like that, maybe that's changed.

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, did you try to use the new option `github-token` with a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)? Would this suit your needs?

**Comment by ericmj** [comment]
We have retries for some of our HTTP calls from https://github.com/erlef/setup-beam/pull/195 and when https://github.com/erlef/setup-beam/pull/196 is done we will have it for all requests.

**Comment by paulo-ferraz-oliveira** [comment]
> We have retries for some of our HTTP calls from #195 and when #196 is done we will have it for all requests.

I was pull requesting yesterday and got loads of errors during tests. I guess that either I don't fully understand the exponential backoff mechanism in `http-client` or it's not working for special cases (e.g. it might be returning a non-400/non-500 mechanism but still the body of the response is unusable).

**Comment by ericmj** [comment]
Can you link to the errors?

**Comment by paulo-ferraz-oliveira** [comment]
Sure, [here's](https://github.com/erlef/setup-beam/actions/runs/4904507357/jobs/8757634902#step:3:14) an example: `{"message":"API rate limit exceeded for installation ID 7037028.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`.

**Comment by lpil** [comment]
> @lpil, did you try to use the new option github-token with a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)? Would this suit your needs?

I've not, no. I can't see any mention of it in the README- where can I read more?

**Comment by ericmj** [comment]
> Sure, [here's](https://github.com/erlef/setup-beam/actions/runs/4904507357/jobs/8757634902#step:3:14) an example: {"message":"API rate limit exceeded for installation ID 7037028.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}.

It should throw an error on rate limit errors https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js#L465-L467. If it's not doing that then I don't know why.

> did you try to use the new option github-token with a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)? Would this suit your needs?

You do not need to use a PAT, all workflows generate a new `GITHUB_TOKEN` and stores it as a secret that you can use: https://docs.github.com/en/actions/security-guides/automatic-token-authentication.

**Comment by paulo-ferraz-oliveira** [comment]
> It should throw an error on rate limit errors https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js#L465-L467. If it's not doing that then I don't know why.

My thoughts exactly. I'd expect either an exception of a proper status code, but I get neither. I'll try to find time to find out why that is.

> You do not need to use a PAT, all workflows generate a new GITHUB_TOKEN and stores it as a secret that you can use: https://docs.github.com/en/actions/security-guides/automatic-token-authentication.

Hm. I was convinced you did require it, which would explain why we added an option in the first place. Maybe I'm convinced it's for this when it's for something else.

https://github.com/erlef/setup-beam/actions/runs/4904507357/jobs/8757634902#step:3:10 < we seem to be using it (passing it, at least), and then having the HTTP client use it too. 🤷

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, is this still relevant? Do you still see issues happening, that are related to this issue?

**Comment by lpil** [comment]
Hello! I've not noticed this happening lately. I think perhaps it is fixed 💜

**Comment by paulo-ferraz-oliveira** [comment]
Feel free to close, and return to it in the future, if it does happen again. 👍

**Comment by lpil** [comment]
Thank you
