### ISSUE TITLE
Support ARM builds

### ISSUE THREAD

**Issue by trashhalo** [erlef/setup-beam#179]
Github actions support arm self hosted runners but setup-beam assumes x86 and errors

```
Installed Erlang/OTP version follows
  .setup-beam/otp/bin/erl: 1: .setup-beam/otp/bin/../erts-13.1.2/bin/dyn_erl: Exec format error
  .setup-beam/otp/bin/erl: 57: exec: ./erts-13.1.2/bin/erlexec: not found
  Error: The process '/home/runner/actions-runner/_work/_actions/erlef/setup-elixir/v1/dist/install-otp.sh' failed with exit code 127
```

**Comment by paulo-ferraz-oliveira** [comment]
True.

Should this come in the form of an env. variable? Or an input? Or how are you executing this in self-hosted runners?

**Comment by trashhalo** [comment]
I was trying the buildjet hosted arm runners. It requires you to change runs-on
runs-on: buildjet-4vcpu-ubuntu-2204-arm

Checking the action docs it does look like the architecture of the runner is available to you already

RUNNER_ARCH
The architecture of the runner executing the job. Possible values are X86, X64, ARM, or ARM64.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... `RUNNER_ARCH`... that should do it, at least for some cases (I'm not sure all our bundled software supports ARM, but I can create a big enough test to validate it and then make sure we incorporate this, somehow). Thanks for your feedback.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... I'm not yet sure how I can test this, actually, unless the online runners (not self-hosted) also support that env. element. If not, it'll have to be by trial-and-error, I guess, maybe with your help.

**Comment by paulo-ferraz-oliveira** [comment]
I started looking into this and it seems that for all the use cases we've considered, the only one where fetching stuff for ARM would be possible is Gleam (and even then only Mac and Linux, no Windows). We fetch our Erlang/OTP builds from Hex, as well as our Elixir builds, and none of them seem to be available for ARM. Maybe @ericmj can further elaborate or even correct me.

**Comment by ericmj** [comment]
Elixir and Rebar are architecture agnostic.

Bob only builds Erlang for x86/x64. We could provide ARM builds also (we do this for docker images already) but the current build scripts assume x86 so they would need to be modified for any changes ARM requires.

https://github.com/hexpm/bob/blob/main/lib/bob/job/otp_checker.ex
https://github.com/hexpm/bob/tree/main/priv/scripts/otp

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, would you accept pull requests to have the builds produce for ARM, and maybe then this action could use those? We can leave this issue open, still, but this is not a limitation the action can directly work around, at the moment, given what is explained above.

**Comment by ericmj** [comment]
Yes, we would accept PRs. I have linked the places where I think changes need to be made in my previous comment.

**Comment by randysecrist** [comment]
Just hit this same issue with github actions using self hosted.  Watching this issue for updates.

**Comment by trashhalo** [comment]
Just in time for the official arm release! https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/
