### ISSUE TITLE
The default configuration provided by Github is broken

### ISSUE THREAD

**Issue by stepchud** [erlef/setup-beam#188]
Hi, I'm setting up GH Actions for the first time on a basic `mix new` project. Github helpfully suggested an Elixir workflow.yml, which looks like this: https://github.com/stepchud/elixirer/commit/ff9f889bb01c1fa6d57f8774c238bfd511b84de4

The build immediately failed:
```
[Build and test](https://github.com/stepchud/elixirer/actions/runs/4804047148/jobs/8549158515#step:3:9)
Tried to map a target OS from env. variable 'ImageOS' (got ubuntu22), but failed. If you're using a self-hosted runner, you should set 'env': 'ImageOS': ... to one of the following: ['ubuntu16', 'ubuntu18', 'ubuntu20', 'win16', 'win19']
```
I'm not familiar with GH Actions or this project so it was a head scratcher. After reading the project README I noticed the following difference from the one GH provides OOTB:
```
-      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
+      uses: erlef/setup-beam@v1
```
That's the only change I needed to get my build passing. I also added the below but I don't think it's necessary here.
```
+        version-type: strict
```
Not sure who owns that GH recommended workflow.yml setup but I thought it might help someone who was trying to setup a new Elixir project with GH Actions. Thanks.

**Comment by stepchud** [comment]
You can also see this happen in this YT clip around the 1 hour mark: https://youtu.be/B9v-PTYgtyY?t=3380

**Comment by paulo-ferraz-oliveira** [comment]
Hello, @stepchud.

The issue is most likely coming from [this](https://github.com/actions/starter-workflows/blob/main/ci/elixir.yml) starter workflow file, not maintained by the maintainers of this actions.

Feel free to pull request there or open an issue to have it looked at.

Thank you.
