### ISSUE TITLE
502 error codes

### ISSUE THREAD

**Issue by pguyot** [erlef/setup-beam#194]
We have been experiencing a lot of 502 errors recently.

For example, on this single run:
https://github.com/atomvm/AtomVM/actions/runs/4851350340/jobs/8645110710
https://github.com/atomvm/AtomVM/actions/runs/4851350340/jobs/8645110116
https://github.com/atomvm/AtomVM/actions/runs/4851350340/jobs/8645111048
https://github.com/atomvm/AtomVM/actions/runs/4851350340/jobs/8645111139
https://github.com/atomvm/AtomVM/actions/runs/4851350340/jobs/8645111537

This does not seem to be related to GitHub API and I am not sure #168 applies.
Maybe considering again hex.pm mirrors again would make sense. Default mirror definitely isn't as reliable as it should be for this action.

**Comment by ericmj** [comment]
I believe mirrors never stop being considered. The PR was closed because it was stale https://github.com/erlef/setup-beam/pull/156.

If you would like to reopen and fix the remaining issues I am sure that would be appreciated.

**Comment by paulo-ferraz-oliveira** [comment]
> I believe mirrors never stopped being considered. The PR was closed because it was stale https://github.com/erlef/setup-beam/pull/156.

This is correct. And as @ericmj replies, re-open the pull request, fixing the remaining issues and re-pull requesting would be appreciated.

**Comment by ericmj** [comment]
It may be better with a new PR since the original one went through a few changes and there's a lot of old comments that do not apply anymore.

**Comment by pguyot** [comment]
Thank you. I did create #197 accordingly.

**Comment by paulo-ferraz-oliveira** [comment]
Closing this since "mirror(s) as an option" is available since #197.
