### ISSUE TITLE
Function `getOTPVersion` does not catch the version being `undefined`

### ISSUE THREAD

**Issue by cgrothaus** [erlef/setup-beam#210]
One of these JS `undefined` vs `null` errors. :sigh:

The safety check starting in line 173 does not catch the version being `undefined`:
https://github.com/erlef/setup-beam/blob/53bf0a5069d1b52da421ab5ba60502856e613797/src/setup-beam.js#L163-L181

That the resolved version can indeed be `undefined` can be seen here:
<img width="1795" alt="otp-version safety check not working" src="https://github.com/erlef/setup-beam/assets/1434706/ca42b1a2-3026-467e-8b4b-255813578a87">

> **Note**
> 
> Regarding the screenshot: that Erlang version 26.0.1 cannot be resolved is another issue, due to caching. See [this comment](https://github.com/hexpm/bob/issues/168#issuecomment-1590655962).

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @cgrothaus.

I'll look into this later, but I'm not sure that's where the issue is (where your pull request changes stuff), actually.

First, because I'm pretty sure we are being strict is using the `!==` and `===` comparisons (look at the rest of the code base); second because if we wanted to go for `null | undefined` we'd probably just go for `!`.

Thanks for the report, though. If something strange's happening it's worth checking out.

**Comment by paulo-ferraz-oliveira** [comment]
Fwiw, we even do `let v = version === null || version === undefined ? null : version` to coerce a version into being `null` if it's undefined, so the issue seems to be somewhere else. Are you, nonetheless, using the latest `@v1` or a specific action version?

**Comment by paulo-ferraz-oliveira** [comment]
`otpVersions.get(otpVersion)` might be returning `undefined`, but I don't see how :173 would benefit from not being compared to `null`, since when `v` leaves `getVersionFromSpec` it's either `null` or a version. But maybe I'm missing something here...

**Comment by paulo-ferraz-oliveira** [comment]
I'm testing this locally and getting

```
::error::Error: Requested Erlang/OTP version (26.0.1) not found in version list (should you be using option 'version-type': 'strict'?)
```

which seems to indicate it's working as expected. Can you create a simple repo. with the issue so I can look at it closer? Thanks.

In my example, the contents of `otpVersions` is

```
  '24.2' => 'OTP-24.2',
  '24.2.1' => 'OTP-24.2.1',
  '24.2.2' => 'OTP-24.2.2',
  '24.3' => 'OTP-24.3',
  '24.3.1' => 'OTP-24.3.1',
  '24.3.2' => 'OTP-24.3.2',
  '24.3.3' => 'OTP-24.3.3',
  '24.3.4' => 'OTP-24.3.4',
  '24.3.4.1' => 'OTP-24.3.4.1',
  '24.3.4.10' => 'OTP-24.3.4.10',
  '24.3.4.11' => 'OTP-24.3.4.11',
  '24.3.4.12' => 'OTP-24.3.4.12',
  '24.3.4.2' => 'OTP-24.3.4.2',
  '24.3.4.3' => 'OTP-24.3.4.3',
  '24.3.4.4' => 'OTP-24.3.4.4',
  '24.3.4.5' => 'OTP-24.3.4.5',
  '24.3.4.6' => 'OTP-24.3.4.6',
  '24.3.4.7' => 'OTP-24.3.4.7',
  '24.3.4.8' => 'OTP-24.3.4.8',
  '24.3.4.9' => 'OTP-24.3.4.9',
  '25.0' => 'OTP-25.0',
  '25.0-rc1' => 'OTP-25.0-rc1',
  '25.0-rc2' => 'OTP-25.0-rc2',
  '25.0-rc3' => 'OTP-25.0-rc3',
  '25.0.1' => 'OTP-25.0.1',
  '25.0.2' => 'OTP-25.0.2',
  '25.0.3' => 'OTP-25.0.3',
  '25.0.4' => 'OTP-25.0.4',
  '25.1' => 'OTP-25.1',
  '25.1.1' => 'OTP-25.1.1',
  '25.1.2' => 'OTP-25.1.2',
  '25.1.2.1' => 'OTP-25.1.2.1',
  '25.2' => 'OTP-25.2',
  '25.2.1' => 'OTP-25.2.1',
  '25.2.2' => 'OTP-25.2.2',
  '25.2.3' => 'OTP-25.2.3',
  '25.3' => 'OTP-25.3',
  '25.3.1' => 'OTP-25.3.1',
  '25.3.2' => 'OTP-25.3.2',
  '25.3.2.1' => 'OTP-25.3.2.1',
  '25.3.2.2' => 'OTP-25.3.2.2',
  '26.0' => 'OTP-26.0',
  '26.0-rc1' => 'OTP-26.0-rc1',
  '26.0-rc2' => 'OTP-26.0-rc2',
  '26.0-rc3' => 'OTP-26.0-rc3',
  'maint' => 'maint',
  '24' => 'maint-24',
  '25' => 'maint-25',
  '26' => 'maint-26',
  'master' => 'master'
```

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, that approach seems more consistent with what I was looking at. Will continue with comments in the pull request.
