### ISSUE TITLE
What is the OTP26 binary?

### ISSUE THREAD

**Issue by pguyot** [erlef/setup-beam#220]
We have a test that fails (weirdly) with the setup-beam OTP26 binary (26.0.1).
It does pass with OTP tag 26.0.1 compiled from source.
It does pass with official docker image tag 26.0.1.
It does pass with setup-beam OTP25 binary.

The test_gc module is the following:

```
-module(test_gc).

-export([start/0]).

start() ->
    {HeapSize, _} = make_a_big_heap(),
    MemorySize = erlang:process_info(self(), memory),
    true = erlang:garbage_collect(),
    NewHeapSize = erlang:process_info(self(), heap_size),
    erlang:display({new_heap_size, NewHeapSize, heap_size, HeapSize}),
    ok =
        case NewHeapSize < HeapSize of
            true -> ok;
            _ -> {fail, new_heap_size, NewHeapSize, heap_size, HeapSize}
        end,
    NewMemorySize = erlang:process_info(self(), memory),
    erlang:display({new_memory_size, NewMemorySize, memory_size, MemorySize}),
    ok =
        case NewMemorySize < MemorySize of
            true -> ok;
            _ -> {fail, new_memory_size, NewMemorySize, memory_size, MemorySize}
        end,
    0.

make_a_big_heap() ->
    LargeBlob = create_blob(512, []),
    HeapSize = erlang:process_info(self(), heap_size),
    {HeapSize, length(LargeBlob)}.

create_blob(0, Accum) ->
    Accum;
create_blob(Len, Accum) ->
    create_blob(Len - 1, [{Len rem 256} | Accum]).
```

The following commands pass:
```
erl -pa . -eval 'erlang:process_flag(trap_exit, false), test_gc:start(), erlang:halt(0).' -noshell
erl -pa . -eval 'R = test_gc:start(), S = 0, erlang:halt(S).' -noshell
erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> 1 end, erlang:halt(S).' -noshell
```

This line fails:
```
erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
```

See this build: https://github.com/pguyot/AtomVM/actions/runs/5382844569
This tree: https://github.com/pguyot/AtomVM/tree/w26/debug-setup-beam-otp-26
This workflow: https://github.com/pguyot/AtomVM/blob/w26/debug-setup-beam-otp-26/.github/workflows/run-tests-with-beam.yaml

**Comment by paulo-ferraz-oliveira** [comment]
The build (for Ubuntu 22.04) should be https://builds.hex.pm/builds/otp/ubuntu-22.04/OTP-26.0.1.tar.gz

What options are used to compile the build? I wouldn't know, but @ericmj should.

Are there any relevant options you're using (or are used in the versions you're using) that might affect that behaviour?

I'm not sure `setup-beam` will be able to solve your problem, but we'll keep this open until we have further info.

**Comment by ericmj** [comment]
I am not sure how I can help here but if you want to debug the build process we use you can look at these files:

- This script invokes builds a docker image and runs the container that builds OTP and then uploads to S3: https://github.com/hexpm/bob/blob/main/priv/scripts/otp/otp.sh
- The dockerfile: https://github.com/hexpm/bob/blob/main/priv/scripts/otp/otp-ubuntu-22.04.dockerfile
- The build script that runs inside the docker container: https://github.com/hexpm/bob/blob/main/priv/scripts/otp/build_otp_ubuntu.sh

**Comment by paulo-ferraz-oliveira** [comment]
> I am not sure how I can help here

I was particularly interested in [the configuration](https://github.com/hexpm/bob/blob/main/priv/scripts/otp/build_otp_ubuntu.sh#L23) you use.

Not sure that makes a lot of difference, in this case. Maybe @pguyot can compare that to the ones used by Docker and arrive at some conclusion (?)

**Comment by pguyot** [comment]
Thank you.
I did test with the following lines, drawing from your scripts:
```sh
export PIE_CFLAGS=-fpie
export PIE_LDFLAGS=-pie
./otp_build autoconf
./configure --with-ssl --enable-dirty-schedulers
make -j
make -j release
```
https://github.com/pguyot/AtomVM/blob/781b77a2356ccb882545750db0f068317e755795/.github/workflows/run-tests-with-beam.yaml#L79-L89

Using either git tag 26.0.1 or the archive OTP-26.0.1 which your script seems to download, however, the test passes where it fails using `setup-beam` action.
https://github.com/pguyot/AtomVM/actions/runs/5386531080

What did I miss?

**Comment by paulo-ferraz-oliveira** [comment]
Now I'm thinking it might be an operating system detail, or even a runner instance detail.

**Comment by paulo-ferraz-oliveira** [comment]
@pguyot, not sure this is an Action -related issue. Shall we close for now and re-open if we happen to find out more? Or do you prefer to keep it open for the time being?

**Comment by pguyot** [comment]
This definitely is an Action issue, or more precisely an issue with the binary downloaded by the action. This bug should not be closed until it is fixed as others may experience problems with the OTP26 binary.

This is not related to a given GitHub Action VM and it doesn't seem to be a concurrency issue as it can be reproduced on every run.

I am curious about what I missed when compiling Erlang OTP from the same source code archive that @ericmj script uses and I believe with the same options.

**Comment by paulo-ferraz-oliveira** [comment]
@pguyot, could you retest using https://github.com/erlef/setup-beam/pull/217? I did some changes to the version matching algo. (long shot, but it's possible something was "fixed")

**Comment by paulo-ferraz-oliveira** [comment]
The version [we get](https://github.com/pguyot/AtomVM/actions/runs/5382844569/jobs/9768816939#step:3:14) seems to be the correct version, though. 🤷

**Comment by pguyot** [comment]
> @pguyot, could you retest using #217? I did some changes to the version matching algo. (long shot, but it's possible something was "fixed")

Same issue as you can see here:
https://github.com/pguyot/AtomVM/actions/runs/5430109549

**Comment by paulo-ferraz-oliveira** [comment]
Ok, so it doesn't seem to be wrong version handling. This is a tough one. Anything you think I should try? (I can give it a go)

**Comment by pguyot** [comment]
I am confused because I used the hexpm script and the error didn't happen.

https://github.com/pguyot/AtomVM/actions/runs/5431586775/jobs/9878047471
https://github.com/pguyot/AtomVM/commit/a2973db13b740480a03dec8dd057db112f07b41b

What's the difference with your attempt?

**Comment by paulo-ferraz-oliveira** [comment]
> I used the hexpm script and the error didn't happen.

I didn't use the Hex.pm script. I used what the action installer itself does. (`wget` from `builds...` then `./Install -minimal $PWD`)

**Comment by pguyot** [comment]
Thank you for the clarification. I understand you confirm that when you use the hex.pm binary, within a local docker environment, the problem occurs.

So far, in spite of my numerous attempts, I haven't been able to build a binary that also exhibits this error on GitHub's workers, including when building using the scripts that @ericmj referred to.

Thanks to your experiment, we know this is not related to GitHub's workers.
I am wondering if there is something wrong with the hex.pm binary or if I built it differently and the problem is with Erlang/OTP.

**Comment by paulo-ferraz-oliveira** [comment]
> I understand you confirm that when you use the hex.pm binary, within a local docker environment, the problem occurs.

Correct.

> I am wondering if there is something wrong with the hex.pm binary or if I built it differently and the problem is with Erlang/OTP.

What I'd want to know, too :)

**Comment by paulo-ferraz-oliveira** [comment]
Hm... now pulling `hexpm/erlang:26.0.1-ubuntu-jammy-20230126` and running the AtomVM test inside yields no errors. Odd!

**Comment by pguyot** [comment]
> Hm... now pulling `hexpm/erlang:26.0.1-ubuntu-jammy-20230126` and running the AtomVM test inside yields no errors. Odd!

Confirming here:
https://github.com/pguyot/AtomVM/actions/runs/5431748696/jobs/9878317162

**Comment by ericmj** [comment]
> Hm... now pulling hexpm/erlang:26.0.1-ubuntu-jammy-20230126 and running the AtomVM test inside yields no errors. Odd!

The docker images are built separately.

@pguyot Have you tried running OTP 26.0.2? Does it have the same issue?

**Comment by pguyot** [comment]
> @pguyot Have you tried running OTP 26.0.2? Does it have the same issue?

I reran the workflow, and OTP 26 specification did pick 26.0.2 as expected.
Unfortunately, as you could see here, it still fails.
https://github.com/pguyot/AtomVM/actions/runs/5431748696/jobs/10139212566

**Comment by paulo-ferraz-oliveira** [comment]
@pguyot, has something changed regarding this issue? Is it still relevant?

**Comment by pguyot** [comment]
@paulo-ferraz-oliveira I confirm the problem is still there.
See this run:
https://github.com/pguyot/AtomVM/actions/runs/5956934899

**Comment by paulo-ferraz-oliveira** [comment]
Ok. Just wanted to understand if you'd looked further at this. Is there a hint to what's causing it?

**Comment by starbelly** [comment]
If you remove the `process_flag/3` call, it'll work 😄  We end with 1598 for the before heap size and 1598 (I think it was 1598) for the new heap size. Without the call, we end up with 4185 as the before heap size and 987 for the new heap size. The sizes of course never going to be 100% the same (gc is non-deterministic even when you force it on yourself AFAIK) coupled with a myriad of other facts that play into all.

That said, it is very strange that this only happens with setup-beam, and while I feel this ultimately will have absolutely nothing to do with this action, and maybe not anything to do with the binary, I'd like to understand what's going on since I can not assert the above to be true.  I think this might get at what @paulo-ferraz-oliveira  was nudging at is a difference in the environment (even if you're using the same erlang/otp version, compiled with the same options, etc.), subtle differences in how everything is executed (what it's executed in) could make a different. Understand, I didn't look deep into this, just some thoughts. 

Here's the success run btw : https://github.com/starbelly/AtomVM/actions/runs/5987955989/job/16242664808

If I can find some time, I'll look further into this. 

I am curious why `process_flag/3` was done here to begin with though?

**Comment by pguyot** [comment]
> The sizes of course never going to be 100% the same (gc is non-deterministic even when you force it on yourself AFAIK) coupled with a myriad of other facts that play into all.

Having worked recently on AtomVM's gc, I can assure you that it's very deterministic, especially as Erlang isolates processes, and when it's not deterministic it's a bug, but that's another story 😁 

> That said, it is very strange that this only happens with setup-beam, and while I feel this ultimately will have absolutely nothing to do with this action, and maybe not anything to do with the binary

What is strange is that the behavior is different and the test passes (as it does with OTP 25):
- when running other binaries of OTP 26.0.1 and 26.0.2 (erlang's official docker images and hex.pm docker images)
- when running a compiled version of OTP 26.0.1 or 26.0.2 generated with supposedly the same build script

And I couldn't find a way to compile OTP that behaves the same as setup-beam's binary.

Hence the question of this issue: what are these binaries that behave differently than other published binaries of OTP 26?
I believe it's a very serious issue. We want the CI to be reproductible and setup-beam's action to be reliably like other binaries of OTP. It's (fortunately) the case with other versions of OTP.

**Comment by paulo-ferraz-oliveira** [comment]
@pguyot, can you post (here) the exact commands you used to build OTP (as if mimicking Bob) from Erlang/OTP's GitHub? The Ubuntu install packages, the download process, the run of autoconf, make, ... I'll do the same, and maybe if there's a difference we can compare stuff. Only thing I see, up to this point, that I'm not used to is `PIE_CFLAGS` and `PIE_LDFLAGS`.

**Comment by paulo-ferraz-oliveira** [comment]
Started a local container with:

```console
docker run -it ubuntu:22.04
```

Ran the following inside (as per what I could collect/trim from @ericmj's links):

```shell
cd $HOME

apt-get update

apt-get install -y \
  wget \
  ca-certificates \
  gcc \
  g++ \
  make \
  automake \
  autoconf \
  libwxgtk3.0-gtk3-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libpng-dev \
  libreadline-dev \
  libncurses-dev \
  libssl-dev \
  libxslt-dev \
  libffi-dev \
  libtool \
  unixodbc-dev \
  fop \
  xsltproc

OTP_REF=OTP-26.0.2
PIE_CFLAGS="-fpie"
PIE_LDFLAGS="-pie"

otp_url=https://github.com/erlang/otp/archive/${OTP_REF}.tar.gz
otp_tar_name=$(basename https://github.com/erlang/otp/archive/${OTP_REF}.tar.gz)
otp_untar_dir="otp-${OTP_REF}"

wget -nv ${otp_url}
tar -zxf ${otp_tar_name}
chmod -R 777 ${otp_untar_dir}

cd ${otp_untar_dir}

# Not required anymore, but exists with status 0
# ./otp_build autoconf

./configure --with-ssl --enable-dirty-schedulers

make -j$(getconf _NPROCESSORS_ONLN)
make -j$(getconf _NPROCESSORS_ONLN) release
make -j$(getconf _NPROCESSORS_ONLN) release_docs DOC_TARGETS="chunks"

# Installing as per setup-bean
export PATH=$PWD/release/bin:$PATH
cd release
./Install -minimal $PWD

# Installed inside /otp-OTP-26.0.2/release/bin and added to PATH
```

(didn't try to run the results of AtomVM tests yet, but will do so later)

**Comment by pguyot** [comment]
> @pguyot, can you post (here) the exact commands you used to build OTP (as if mimicking Bob) from Erlang/OTP's GitHub? The Ubuntu install packages, the download process, the run of autoconf, make, ... I'll do the same, and maybe if there's a difference we can compare stuff. Only thing I see, up to this point, that I'm not used to is `PIE_CFLAGS` and `PIE_LDFLAGS`.

FYI, one of the workflow jobs does run the scripts mentioned by @ericmj with a small patch related to aws and fastly:
https://github.com/pguyot/AtomVM/blob/2370047355b6620b21681c457d8f83f8f370bba1/.github/workflows/run-tests-with-beam.yaml#L130-L151

And when it does, the test passes.
https://github.com/pguyot/AtomVM/actions/runs/5956934899/job/16158719159

**Comment by starbelly** [comment]
One difference between the hexpm script runs above and setup that I can see is one is Docker in Docker (I think that's right?) the other (setup-beam) is not... is that correct?

**Comment by starbelly** [comment]
Okie dokie. 

I did a run here : https://github.com/starbelly/AtomVM/actions/runs/5991376175/job/16249678919

Pinning to v1.15.4 

Here are the release notes for the latest : https://github.com/erlef/setup-beam/releases/tag/v1.16.0

Something in there is the issue, the main culprit to me is tools cache, as that's perhaps the biggest change. How that effects ERTS is mind boggling, but a vague hypothesis based on experiments last night would suggest something is running slower or faster (depending on how you look at ). With v1.16.0 the process kicks off with 1598 heap sized (used parts), it stays this way through out the entire life cycle. I could only change that behaviour by removing the process_exit/2 call or inserting two gc calls. This tells me there's an issue with locking (i.e., when you call process_info/2 to get heap size info that data has not / can not be updated yet because of previous operations still holding locks). Vague hypothesis, but it's what I have right now 😄

**Comment by starbelly** [comment]
What would be interesting is to add `-init_debug` to that last erl call. You'll have to do several runs and compare the numbers across all. Which sets (loading modules, starting applications, etc.) are going slower (or faster) compared to setup-beam with tool-cache involved?

It might also be worth adding setup-beam prior to tools-caching to the matrix in such a comparison.

**Comment by paulo-ferraz-oliveira** [comment]
I've now added

```console
apt-get install git
cd $HOME
git clone https://github.com/atomvm/AtomVM
cd AtomVM
erlc tests/erlang_tests/test_gc.erl
erl -pa . -eval 'erlang:process_flag(trap_exit, false), test_gc:start(), erlang:halt(0).' -noshell
erl -pa . -eval 'R = test_gc:start(), S = 0, erlang:halt(S).' -noshell
erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> 1 end, erlang:halt(S).' -noshell
erl -pa . -eval 'R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
erl -pa . -eval 'erlang:process_flag(trap_exit, false), R = test_gc:start(), S = if R =:= 0 -> 0; true -> io:format("Expected ~B, got ~p~n", [0, R]), 1 end, erlang:halt(S).' -noshell
```

to the previous script and all exit codes are 0. That is funny, but I have to remember I don't have the same env. as GitHub actions (the Ubuntu runner) to start with, so that's why that's my hypothesis (that a change in that causes the issue).

**Comment by paulo-ferraz-oliveira** [comment]
I'm going to try with other images (these are the ones [nektos/act](https://github.com/nektos/act) uses, so I guess are closer to GHA's then `ubuntu:22.04`):

* `node:16-bullseye-slim`:... (later)... tests without error
* `catthehacker/ubuntu:act-22.04`: ... (later)... tests without error

We could try to pursue @starbelly's avenue of "tool-cache", in this case. Maybe start by looking at the code and checking if something's funny there (?)

**Comment by starbelly** [comment]
> I'm going to try with other images (these are the ones [nektos/act](https://github.com/nektos/act) uses, so I guess are closer to GHA's then `ubuntu:22.04`):
> 
>     * `node:16-bullseye-slim`:... (later)... tests without error
> 
>     * `catthehacker/ubuntu:act-22.04`: ... (later)... tests without error
> 
> 
> We could try to pursue @starbelly's avenue of "tool-cache", in this case. Maybe start by looking at the code and checking if something's funny there (?)

I mean, a glance at the code shows nothing funky, further it just works ™️ . However, we know something changed, while I didn't not exhaustively test 1.16.0 and 1.15.x, it seemed to be that at 1.16 things don't work (particularly for this kind of test, nothing else has issues). So, it really starts going into exotic problem territory, which I don't like, but may be exactly what it is. 

It would be helpful for others to test 1.15.x vs 1.16.0 to confirm that finding. 

Other things we know : 

1. When we use tool-cache, everything is located outside of our `$HOME`  (at least it appears that way on the surface, how github implements all this behind the scenes I have no idea). 
2. Putting in a small delay before the `process_flag/2` call "fixes" the issue.
3. Removing the`process_exit/2`call "fixes" the issue.
4. Putting in an extra major gc call "fixes" the issue. 
5. The eval of the string and execution of the code therein is happening concurrently with other processes doing other "things" (see init.erl). 

Probably left out a few things, i've provided speculation in other comments and will leave it at that for now 😄

**Comment by pguyot** [comment]
@paulo-ferraz-oliveira @starbelly thank you so much for this work.
Especially for showing the test fails without setup-beam which can rule out the action.

With more experiments based on your results, it seems that the problem does occur when `./Install -minimal` is used as opposed to `make install`. Isn't it the major difference with the docker images?
The installation tree is a little bit different in this case, as well as file `installed_application_versions`, but I was able to rule out the file.

I have yet to determine in which condition it works with version 1.15.4, as I understand from [this line](https://github.com/erlef/setup-beam/blob/c2e02f777c158310fc6d3d4e11b36a52d2d52db8/src/install-otp.sh#L16) it also uses `./Install -minimal`.

**Comment by starbelly** [comment]
> @paulo-ferraz-oliveira @starbelly thank you so much for this work. Especially for showing the test fails without setup-beam which can rule out the action.
> 
> With more experiments based on your results, it seems that the problem does occur when `./Install -minimal` is used as opposed to `make install`. Isn't it the major difference with the docker images? The installation tree is a little bit different in this case, as well as file `installed_application_versions`, but I was able to rule out the file.
> 
> I have yet to determine in which condition it works with version 1.15.4, as I understand from [this line](https://github.com/erlef/setup-beam/blob/c2e02f777c158310fc6d3d4e11b36a52d2d52db8/src/install-otp.sh#L16) it also uses `./Install -minimal`.

That's interesting if proven, it would jibe with the idea that "we're going faster now" (though I still think this is a bit fancy, but possible). With minimal sasl is not started, that's pretty much it.

**Comment by pguyot** [comment]
> That's interesting if proven, it would jibe with the idea that "we're going faster now" (though I still think this is a bit fancy, but possible). With minimal sasl is not started, that's pretty much it.

Drawing from the repro case that doesn't involve setup-beam action, I ran more experiments here, including with the `-init_debug` option you suggested.

https://github.com/pguyot/AtomVM/actions/runs/6056279155/job/16436166344

I tried various combinations including to bisect the commit that fails. The same binary is installed and run from `${prefix}/bin`, from `${prefix}/lib/erlang/bin` and from the release that was `./Install`'d. Only this last run fails, including when `${prefix}` is next to it (I tried to rule out VM mounts).

With `./Install -sasl`, the problem doesn't occur, although I did confirm that `make install` doesn't put sasl in the applications to start at boot by default.

**Comment by starbelly** [comment]
> With `./Install -sasl`, the problem doesn't occur, although I did confirm that `make install` doesn't put sasl in the applications to start at boot by default.

The output here shows that it is loaded and started up : https://github.com/pguyot/AtomVM/actions/runs/6056279155/job/16436174003
