### ISSUE TITLE
Have the action output a versioning element so it could be used as part of the cache restore key

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#222]
When we release a new version, like 1.16 (that "broke" cached PLTs), this could help avoid some issues on consumers.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira  I think that's an excellent idea. I suppose this only effected folks using the tag in their cache key previously?

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, the problem is how to get the version exposed, I guess :) Should we start maintaining it inside the code and updating it prior to every release?

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira Yeah, I mean, we could stick it in a file in the repo, just need to come up with a way to ensure it gets updated vs depending on diligence.
