### ISSUE TITLE
Warnings output in tests

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#23]
Most probably innocuous, but these two warnings are output in Pre-release integration tests and may be misleading (not everybody contributing to the Action will eventually know Elixir):

* `variable "deps" does not exist and is being expanded to "deps()" ...`
* `variable "description" does not exist and is being expanded to "description()" ...`

We should aim to getting rid of them if there's no particular reason for them to be there.

**Comment by ericmj** [comment]
Can you link to the warnings?

**Comment by paulo-ferraz-oliveira** [comment]
Sure. Eric, check https://github.com/erlef/setup-beam/actions/runs/702116828 (> Annotations). Right-hand side, at the bottom.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira These are warnings per  problems in the `mix.exs` of the logfmt project, this is expected. These should be fixed by the author of said lib. I guess I'm confused why this effects us? We can always just switch to another dep if it's confusing, no?

**Comment by paulo-ferraz-oliveira** [comment]
It doesn't affect the tests (or _us_); it's just that there's warnings in the output and they were misleading to me. I didn't know if it was pertinent or not (now I do, as per your reply).
