### ISSUE TITLE
Update to use Node.js 20

### ISSUE THREAD

**Issue by talklittle** [erlef/setup-beam#243]
#### Is your feature request related to a problem?

GitHub Actions reports this warning: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: erlef/setup-beam@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."

#### Describe the feature you'd like

Update this action to use Node.js 20

#### Describe alternatives you've considered

Continue using deprecated Node.js 16 and seeing the warning

#### Additional context

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by paulo-ferraz-oliveira** [comment]
Maybe I'll recover what's similar to https://github.com/erlef/setup-beam/pull/236, that was previously closed for being stale. Thanks...

**Comment by paulo-ferraz-oliveira** [comment]
v1.17.2 released
