### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by essen** [erlef/setup-beam#261]
#### The bug

Just got a request timeout fetching repo info:

https://github.com/ninenines/cowlib/actions/runs/8434678847/job/23098464908

```
Error: Request timeout: /repos/erlang/otp/releases?per_page=100&page=2
```

#### How to replicate

Probably hard to.

#### Expected behaviour

I would expect HTTP clients that time out to try again a few seconds later for at least a couple times before giving up.

**Comment by starbelly** [comment]
The the toolkit provides retry functionality, I suppose it's in order to give this a whirl. We may also need to consider a new approach to caching, though that of course has problems. This relates to #260

**Comment by paulo-ferraz-oliveira** [comment]
Closing in favor of #261. Feel free to re-open if you think this is not the correct course of action. Cheers.
