### ISSUE TITLE
Have Erlang/OTP 17-19 work with Ubuntu 18.04

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#28]
For history look at this one: https://github.com/hexpm/bob/issues/82.

**Comment by starbelly** [comment]
So the issue is the installed openssl version? Is that right? 

If so, one idea which builds on @wojtekmach's ongoing work with `beamup` is to include ssl in the build, but that's not a quick thing to do AFAIK.

 A quicker hack would be something like @ericmj's suggestion of installing an additional openssl package and modifying lib paths so erlang looks to it on load. I think this would be a good path vs changing the primary openssl package already installed as I can only imagine how many deps apt will complain about and/or break by removing the already installed version.

**Comment by wojtekmach** [comment]
> If so, one idea which builds on @wojtekmach's ongoing work with beamup is to include ssl in the build, but that's not a quick thing to do AFAIK.

it is just a matter of passing `—disable-dynamic-ssl-lib` when building OTP.

that being said, in light of that big OpenSSL vulnerability this week I’m more skeptical about baking in a particular version. For macOS that might be the only option since Apple actively tells devs that they should not depend on system openssl which is deprecated and there just for backwards compat.

**Comment by paulo-ferraz-oliveira** [comment]
> it is just a matter of passing —disable-dynamic-ssl-lib when building OTP.

Hm... @ericmj previously proposed that "The build is likely correct" (vide comment in initial description). My initial approach would be to just do something similar to https://github.com/hexpm/bob/blob/master/priv/scripts/docker/erlang-ubuntu-bionic.dockerfile#L44. Locally, in my machine, I've always had to use a different version of SSL up until 20.3, potentially for similar issues we're experiencing.

**Comment by ericmj** [comment]
The build is likely correct, but that doesn't mean we can't build with `--disable-dynamic-ssl-lib`, that's unrelated to build correctness.

I agree with @wojtekmach that we should not statically link SSL because then it's our job to make sure we ship with a secure version. I would suggest to instead investigate if we can change the installed versions of `libssl` to one that is compatible with the linked version.

**Comment by starbelly** [comment]
Yeah, that makes sense to me. I would try installing ssl to an alternative path and making use of env vars so the erlang sees that vs the pre-packaged version. Rationale is trying to change the libssl version completely will result in a lot of headaches around installed packages, but it's up to whomever wants to give this a go as far as which route to try first.

**Comment by wojtekmach** [comment]
> I would try installing ssl to an alternative path and making use of env vars so the erlang sees that vs the pre-packaged version.

which env vars? My understanding is when we dynamically link ssl to OTP (specifically, say, we dynamically link openssl's libcrypto to $OTP_ROOT/lib/crypto/priv/lib/crypto.so) the path to the dynamic library is hardcoded into the object file so it's not something we can easily control. I believe a solution is to have post-install to rewrite paths in shared object files (which has interesting problems on macOS in particular if these files are _signed_), is that what the env vars are supposed to do?

**Comment by starbelly** [comment]
@wojtekmach Right but on load, it's going to look for openssl, if you modify the search path (if you will) you should be able to load the installed version we want, is my thinking. After all, that's the "pro" of dynamic linking (despite the security problems it brings to the table). 

If the problem is the installed openssl version on certain versions of ubuntu, this should do the trick, I believe.

**Comment by wojtekmach** [comment]
> if you modify the search path (if you will) you should be able to load the installed version we want, is my thinking.

can you be specific how that can be done?

**Comment by starbelly** [comment]
Say we install openssl to /usr/local 

`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

**Comment by wojtekmach** [comment]
doh, of course, thanks!

**Comment by paulo-ferraz-oliveira** [comment]
> The build is likely correct, but that doesn't mean we can't build with --disable-dynamic-ssl-lib, that's unrelated to build correctness.

I understand this, but @wojtekmach's reply states "It is just a matter of..." and while you can dynamically link, it's not "just" the only thing that's required, surely (Erlang/OTP 19 had different `ssl` requirements than 20+).

**Comment by paulo-ferraz-oliveira** [comment]
I'll try "I would try installing ssl to an alternative path and making use of env vars so the erlang sees that vs the pre-packaged version." with the change to the env. variables.

**Comment by paulo-ferraz-oliveira** [comment]
At a first glance it seems app `ssl` isn't being built. I'm going to try and simulate what `bob` does, locally, to figure out if I can understand more of the problem. If you have any ideas on how to proceed, also, write them here so I may try to find time to pursue them.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, so in this system I build, looking at what `bob` does in "FROM ubuntu:${OS_VERSION} AS build", I get:

```erlang
> crypto:start().
ok

> application:ensure_all_started(ssl).
{ok,[asn1,public_key,ssl]}
```

From the pre-built system, I get:

```erlang
> crypto:start().
** exception error: undefined function crypto:start/0

> application:ensure_all_started(ssl).
{error,{ssl,{"no such file or directory","ssl.app"}}}
```

**Comment by paulo-ferraz-oliveira** [comment]
These ones are not not found in the `.tar.gz` downloaded from Hex.pm:
* `crypto-3.7.3`
* `ssh-4.4.1`
* `ssl-8.1.1`
I'm not sure how they're not making their way to the tarball, since when using `bob`'s process locally they are being generated.

**Comment by paulo-ferraz-oliveira** [comment]
FWIW, `apt-get install -y wget` (part of `bob`'s procedure) installs `openssl` (in Ubunt 18.04's case, this is 1.1.1).

**Comment by paulo-ferraz-oliveira** [comment]
How's `hexpm/19.3-ubuntu-bionic-20200219` Docker image built? It contains the lib.s I previously mentioned not present in the `.tar.gz` image.

**Comment by paulo-ferraz-oliveira** [comment]
So, one way I could overcome the non-building of those app.s was to change https://github.com/hexpm/bob/blob/master/priv/scripts/otp/build_otp_ubuntu.sh#L31 from `-with-ssl` to `--with-ssl=/usr/local/ssl`, but I'm not sure how this'd impact the `bob`'s builds.

**Comment by paulo-ferraz-oliveira** [comment]
## SSL dynamic linking

I run into several hurdles trying to use `--enable-dynamic-ssl-lib` but will eventually update this if I can get it to work.

**Comment by paulo-ferraz-oliveira** [comment]
The 2 previous attempts are related to the build process itself, not the action. I was trying to figure out if we could tweak the build result via env. var.s or similar, but it doesn't seem feasible (at least as easily as it would be changing the Hex.pm image). I'll leave the issue open until you figure out where the fix should occur.

**Comment by starbelly** [comment]
Since this doesn't work out of the box devoid of this action, I'm unsure as to why we're trying to deal with it here?

**Comment by paulo-ferraz-oliveira** [comment]
I was just trying to learn what could make it work, actually, but kinda feels it shouldn't be here (except for the fact that the action is indirectly affected by it). I think it's OK to be closed.

**Comment by ericmj** [comment]
> do you think this means a fix has to be done other than in the action itself?

The docker images work so you will have to describe your steps more in order for us to figure out why it doesn't work for you.

```
> docker run -it hexpm/erlang:19.3-ubuntu-bionic-20200219 sh
Unable to find image 'hexpm/erlang:19.3-ubuntu-bionic-20200219' locally
19.3-ubuntu-bionic-20200219: Pulling from hexpm/erlang
423ae2b273f4: Pull complete
de83a2304fa1: Pull complete
f9a83bce3af0: Pull complete
b6b53be908de: Pull complete
993127a90d93: Pull complete
c31078cabf93: Pull complete
Digest: sha256:de9c8af1c6e52a6935d98adb2d4f6403af6ed93b48a2fbc67ebaeeb6677ddea2
Status: Downloaded newer image for hexpm/erlang:19.3-ubuntu-bionic-20200219
# erl
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3  (abort with ^G)
1> ssl:start().
ok
2>
```

**Comment by ericmj** [comment]
Fixed the issue, ssl is now included. Rebuilding all versions will take a few hours.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, thanks for looking at this and re-generating the images. If all goes well, we can:

- [ ] broaden the tests, and take those specific combos into account
- [ ] potentially get rid of the Compatibility Matrix (at the very least, tweak it)

👍

**Comment by ericmj** [comment]
Although I haven't tested this, I think that even with the builds fixed we need to use another version of `libssl` in the action. So there is still some testing and possibly work to be done.

**Comment by starbelly** [comment]
Sweeeet!! Thank you @ericmj !!! 💜

**Comment by wojtekmach** [comment]
I run a test and it worked perfectly in all but two combinations (`ubuntu-20.04, 1.5.3, 18.3.4.11` and `ubuntu-20.04, 1.7.4, 19.3.6.13`), see the results: https://github.com/wojtekmach/setup-elixir-bug/runs/2281881985?check_suite_focus=true and the test: https://github.com/wojtekmach/setup-elixir-bug/blob/master/.github/workflows/ci.yml.

Well done and thanks everyone involved!

**Comment by paulo-ferraz-oliveira** [comment]
> Although I haven't tested this, I think that even with the builds fixed we need to use another version of libssl in the action. So there is still some testing and possibly work to be done.

Cool. What did you have in mind?

**Comment by paulo-ferraz-oliveira** [comment]
@wojtekmach, those results are expected, right? The listings don't contain Ubuntu 20.04 Erlang pre-20. (also, we now have an indication in [the compat. matrix](https://github.com/erlef/setup-beam#compatibility-between-ubuntu-and-erlangotp))

**Comment by wojtekmach** [comment]
Yup, all good.

**Comment by paulo-ferraz-oliveira** [comment]
As per the title, and then PR https://github.com/erlef/setup-beam/pull/31, should we go ahead and close this issue?

**Comment by paulo-ferraz-oliveira** [comment]
Closing this as resolved (per title and https://github.com/erlef/setup-beam/pull/31's results). Please re-open if deemed otherwise.
