### ISSUE TITLE
Setting ImageOS to ubuntu24 does not work.

### ISSUE THREAD

**Issue by ankhers** [erlef/setup-beam#280]
#### The bug

I have a self hosted runner and I have set the `ImageOS` to be `ubuntu24`. However, when I do this, I get the following error.

> Error: Tried to map a target OS from env. variable 'ImageOS' (got ubuntu24), but failed. If you're using a self-hosted runner, you should set 'env': 'ImageOS': ... to one of the following: ['ubuntu18', 'ubuntu20', 'ubuntu22', 'win19', 'win22']
Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/6129ca00-2288-11ef-945a-71eb091f6d2b.sh], exit code 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.

The readme says that `ubuntu24` should be a valid value.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* `setup-beam`: @v1 (I don't know how to see the exact version that was pulled)

#### How to replicate

An ordered list of steps to replicate the bug:

1. Use the this action on a self hosted runner
2. Set the `ImageOS` to be `ubuntu24`
3. See the above error

#### Expected behaviour

Since using `ubuntu24` is documented in your README, I would expect it to work.

#### Additional context

Any other context about the bug.

**Comment by paulo-ferraz-oliveira** [comment]
👋 

> I don't know how to see the exact version that was pulled

This is the detail 😄 

The README's been updated in the main branch, but the main branch is not representative of the latest release, only the most up-to-date code.

As such, `v1`, at the moment you used the action, most likely pulled https://github.com/erlef/setup-beam/tree/v1.17.5, where the README does not mention `ubuntu24`.

In any case, I'm gonna cut a release soon. When that's done (I'ma warn about it here) feel free to test it out and then close the issue if you don't see it anymore.

Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
`v1.17.6` has been released. I'm moving `v1` and `v1.17` to it.

**Comment by paulo-ferraz-oliveira** [comment]
* https://github.com/erlef/setup-beam/tree/v1
* https://github.com/erlef/setup-beam/tree/v1.17
* https://github.com/erlef/setup-beam/tree/v1.17.6

all point to the same commit, at this moment.

**Comment by paulo-ferraz-oliveira** [comment]
Closed by https://github.com/erlef/setup-beam/pull/271.
