### ISSUE TITLE
Optionally install Eqwalizer / ELP

### ISSUE THREAD

**Issue by robertoaloi** [erlef/setup-beam#283]
[`eqwalizer`](https://github.com/WhatsApp/eqwalizer) is a type checker for Erlang.

[`ELP`](https://whatsapp.github.io/erlang-language-platform/) or `Erlang Language Platform` has a powerful CLI that can be used as a linter to detect (and autofix) unused macros, unused headers and other bad smells in code.

See, for example, usages in [RabbitMQ](https://github.com/rabbitmq/rabbitmq-server/pull/11305) and [brod](https://github.com/kafka4beam/brod/pull/575).

It would be great to have both `eqwalizer` and `ELP` as optional installations for the `setup-beam` action, as this would enable users to be able to perform validation for their code base during CI with minimal effort.

Binary executables are [provided](https://github.com/WhatsApp/erlang-language-platform/releases/tag/2024-06-07) for both Linux and Mac. Installation from source is documented [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/install/).

**Comment by paulo-ferraz-oliveira** [comment]
👋 I'm not sure the action should support this. We're basically an installer for pre-compiled elements that support code development, like the compilers and runtimes. Having this here would open the door to start having `rebar3_lint`, `rebar3_format`/`erlfmt`, `rebar3_hank`, etc. since these are all lib.s (even if not pre-compiled and Erlang/Elixir -ish). Fwiw, for example, we also don't install `dialyxir` as a means to ease CI on Elixir projects. Maybe I'm missing something on your intent, but I feel this can be easily covered with an example Gist on how to do it.

**Comment by paulo-ferraz-oliveira** [comment]
👋 I'm not sure the action should support this 😄, but I'm listening. We're basically an installer for pre-compiled elements that support code development, like the compilers and runtimes. Having this here would, maybe, open the door to start having `rebar3_lint`, `rebar3_format`/`erlfmt`, `rebar3_hank`, etc. since these are all lib.s that support development (even if not pre-compiled and Erlang/Elixir -ish). Fwiw, for example, we also don't install `dialyxir` as a means to ease CI on Elixir projects. Maybe I'm missing something in your intent, but I feel this can be easily covered with an example Gist on how to do it (?)

**Comment by paulo-ferraz-oliveira** [comment]
> Maybe having a separate action for those could be a good compromise?

I believe so, and the same for Eqwalizer / ELP. What you're getting from `setup-beam` is a thin layer around "grab this version of this tool and install it", but focused on BEAM and higher-level languages. And I'd be Ok to participate in implementation or help out if required.

**Comment by robertoaloi** [comment]
Some help on this would be terrific! I have never contributed an action before but I can help with the ELP parts, what's the best way to make this happen?

**Comment by paulo-ferraz-oliveira** [comment]
By separate action I mean a separate repo. Is that what you were thinking, too? I think we could start by having a name for the action, and a repo. (@starbelly would be able to create a repo., I can't - or maybe even you, I see you in the org.s members, but don't know if you're an admin). Then I could create a small skeleton for it, and you'd fill in the blanks. 😄

**Comment by robertoaloi** [comment]
`erlef/setup-elp` sounds like the most obvious one. A skeleton would help!

**Comment by robertoaloi** [comment]
Also yes, it looks like I can create repos O_o
Not sure where the super-power comes from.

**Comment by paulo-ferraz-oliveira** [comment]
> Not sure where the super-power comes from.

You're a member of the `erlef` org. and possibly also an admin. 😄 

---

Once you create the repo. I can upload a minimal action to it (I created something yesterday, already); I think I just need to be an external collaborator (to go fast), or otherwise I need to pull request. And then we can discuss more details there, like the interface and where the assets are fetched from, etc.

**Comment by robertoaloi** [comment]
I'm apparently a member of one of the teams. But I don't want to abuse my powers since I don't know if that's intentional. Let's wait until @starbelly gives a go-ahead.

**Comment by paulo-ferraz-oliveira** [comment]
In the meantime, Roberto, could you tell me:

* what are the expected inputs? Maybe it's just the versions of the tools? And are they semver or something else?
* where to obtain the tools from (and what architectures are available)?
* what outputs would you expect the action to make available?

**Comment by starbelly** [comment]
I like this idea 😄 We just need it to run through build-and-packaging to see what the general thought is. At the start, we made a decision that we didn't want to have too many projects under the umbrella of the erlef as people didn't want this to end up like the apache foundation (where projects go to die). I don't think that's the case here what so ever, but it would be remiss of me not run it by the working group first.

**Comment by yordis** [comment]
It could be added under https://github.com/erlef/gh-actions/tree/main/stable, which was the intent of the repo.

I am trying to prove a few things across multiple Elixir (sorry, I do not have much Erlang experience in CI) before I start moving some common setups.

**Comment by yordis** [comment]
It could be added under https://github.com/erlef/gh-actions/tree/main/stable, which was the intent of the repo.

Before moving some typical setups, I am trying to prove a few things across multiple Elixir (sorry, I only have a little Erlang experience in CI); all I would ask is to be as generic but tackle the 80/20 situation.

```yaml
- use: erlef/gh-actions/stable/setup-elp@v0.1.1
```

**Comment by robertoaloi** [comment]
That would be perfect. We could also publish it in a private repo (@paulo-ferraz-oliveira's ?) for the time being and eventually transfer it to the erlef once it goes through the build-and-package working group.

> What are the expected inputs? Maybe it's just the versions of the tools? And are they semver or something else?

We can probably start with the ELP version only. Eqwalizer is packaged in there. The version has the format `YYYY-MM-DD` or `YYYY-MM-DD_N` if there are multiple releases per day. No semantic versioning.

> Where to obtain the tools from (and what architectures are available)?

Binaries are published as release assets. Example [here](https://github.com/WhatsApp/erlang-language-platform/releases/tag/2024-06-07).

We currently provide binaries for Linux (`x86_64` and `aarch64`) and Mac `x64_64`. There's also a Mac `aarch64` but I think the eqwalizer artifact is still for `x64_64` in there (we should fix that, but I believe there was no runner available for that platform). All artifacts are currently available for OTP 25 and OTP 26.

We probably need to depend on `setup-graalvm` to be able to run Eqwalizer.

All the magic happens [here](https://github.com/WhatsApp/erlang-language-platform/blob/main/.github/workflows/ci.yml).
Installation instructions from binary are also available [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/install/#from-binary).

> What outputs would you expect the action to make available?

I would expect the `elp` CI to be available in the pipeline so that commands such as `elp eqwalize` and `elp parse-elp` can be used to perform, respectively, type checking and linting (similar to `rebar3 dialyzer` and `rebar3 elvis`.

**Comment by starbelly** [comment]
@robertoaloi  I think people think this is a good idea 😄 I can go ahead and make a repo, are you still wanting to go with `setup-elp`? Just let me know

**Comment by robertoaloi** [comment]
@starbelly `setup-elp` would be perfect!

**Comment by starbelly** [comment]
@robertoaloi done. I kicked it off as private, feel free to change at your digression 😄

**Comment by robertoaloi** [comment]
@starbelly Thanks!

@paulo-ferraz-oliveira is the one who will probably publish the first skeleton. Do you have access to it?

**Comment by paulo-ferraz-oliveira** [comment]
> Do you have access to it?

Seems not 😢

**Comment by paulo-ferraz-oliveira** [comment]
Moved to the reference mentioned above.
