### ISSUE TITLE
Move some tags

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#33]
This got left behind in some other thread, so having it here for decision time™️.

"
I'm still confused with:
* 1.0.0 not having v (probably nothing to see here)
* v1.4.1 being paired with v1.4, and not v1.4.2 (should we move the tag?)

Should we push v1.6 and v1.7 where applicable? (should we?)
"

There's two questions above.

**Comment by paulo-ferraz-oliveira** [comment]
Actually, the v1.6 and v1.7 bit is done, but v1.4 isn't (I'm not sure what it would entail, since it predates my participation in the project).

**Comment by jclem** [comment]
In general, the way I'd originally been handling tags in this project (and the way we handle tags for many of the first-party actions GitHub provides) is that I'll force-push every relevant tag that matches a new release.

For example, if I'm releasing v1.5.2, I create that tag and also move the existing v1.5 and v1 tags. Likewise, if I'm creating v2.7.0, I create that tag, create the v2.7 tag, and move the existing v2 tag. For a new major version v3.0.0, I create all of v3.0.0, v3.0, and v3 and move no tags.

Of course, whether you all choose to continue with that way of doing releases is your call. Generally, I consider full semver tags to be stable, and partial tags to be movable in Actions-land, but this is purely by convention.

**Comment by paulo-ferraz-oliveira** [comment]
I agree with what you said. I asked because there could've been a special reason for v1.4 to remain "off" like this. I wasn't here, so I don't know 😄, but generally speaking I'd do the same as you, as I could infer from what was done already. I'll move the tag accordingly.

**Comment by paulo-ferraz-oliveira** [comment]
Moved v1.4 to be the same as v1.4.2.
