### ISSUE TITLE
Print installed rebar3 version

### ISSUE THREAD

**Issue by wojtekmach** [erlef/setup-beam#37]
Currently we print the installed Erlang version and, if `elixir-version` is set, the Elixir version. Given we also install rebar3, I think it'll be useful to see which version was picked for us if we don't set `rebar3_version` param.

**Comment by paulo-ferraz-oliveira** [comment]
@wojtekmach, does this mean **unconditionally** print it? I think that should be fine, sure, assuming that it will always be present (not sure if that'll be the case if, in the future, we add other languages, though, but we can revisit then).

**Comment by wojtekmach** [comment]
Yes, print it unconditionally as it is always installed. If in the future for some reason it stops being always installed, which I probably wouldn't do, then we'd not print it.

**Comment by wojtekmach** [comment]
we always do, this workflow file:

https://github.com/wojtekmach/test_erlang/blob/941a83d52e62a6f2c6e0ce5ed62b2f287ea4a232/.github/workflows/main.yml#L13

worked:

https://github.com/wojtekmach/test_erlang/runs/2674428182

I think it is useful to automatically install rebar3.

**Comment by paulo-ferraz-oliveira** [comment]
I see. Is that one coming from the Erlang we download from Hex.pm?

**Comment by wojtekmach** [comment]
I don't know where it comes from but it doesn't seem to be the one installed by Hex. These are the ones we manage:

```
 curl https://repo.hex.pm/installs/rebar3-1.x.csv
3.13.1,1323dec786a1642c50c29cf6601bc4e1888de9918527676b657394f75dfb873ce8b27d818ceaed4f76bcbc615cd14680e2ce2027e7d7d37e4db575be29574cd0,1.0.0
3.14.4,2dd29a56466df44ccc0229fafe209c8818bedd44cfedca3917eba427992ef767e39b7fd9281bb42f558770114fd83b8cf8d93b092126870f9b48caabaf9c4d99,1.11.4
```

**Comment by paulo-ferraz-oliveira** [comment]
> I don't know where it comes from...

Ah, let me dig into this. I'm not sure where it's coming from either. 😄

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/actions/virtual-environments/blob/ubuntu20/20210517.1/images/linux/Ubuntu2004-README.md does mention Erlang 24, but not `rebar3`, although I don't think it's too odd to consider that the bundle contains both given the results of https://github.com/erlef/setup-beam/runs/2674523072?check_suite_focus=true.

**Comment by wojtekmach** [comment]
Oh, interesting! That explains it. I was also able to verify it:

```yaml
- run: which rebar3
```

```
/usr/local/bin/rebar3
```

I'm gonna go ahead and close this then, sorry for the noise!

**Comment by paulo-ferraz-oliveira** [comment]
@wojtekmach, I don't mind printing the version 😄, especially when `rebar3` is effectively present. I'd just be sure to check if the executable exists, in that case.

Do you think we shouldn't pursue this in the conditions I mention?

**Comment by wojtekmach** [comment]
Since this rebar3 installation is out of our control I don't know what we should do. If you decide to print the version maybe we should mention it is a system installation and not a setup-beam one.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... yeah, in that case I do consider it becomes more confusing. Let's see if somebody else comes along with the same "issue"/suggestion then we can address it.

**Comment by starbelly** [comment]
If I've grokked the issue correctly we can simply put the two paths we know we will want to refer to with first on `$PATH`. Namely `~/.setup-beam/bin` and '~.mix/` (or ~/.setup-beam/.mix`). Then we should always hit one or the other vs a system install of rebar3. Thoughts?

**Comment by paulo-ferraz-oliveira** [comment]
We're already targeting the proper `rebar3` when that's asked for by the consumer. If it's not, well, he/she is using the system `rebar3`. What could be considered is using an image that doesn't have Erlang+rebar3 to start with, or otherwise have the action remove that (which would be odd, at the least).
