### ISSUE TITLE
rebar3 broken on OTP 17-20

### ISSUE THREAD

**Issue by wojtekmach** [erlef/setup-beam#40]
Hi, I noticed rebar3 is broken on OTP 17-20. See example project: https://github.com/wojtekmach/test_erlang/pull/1/checks

I know for a fact it was working well not that long ago, see https://github.com/hexpm/hex_core/actions/runs/861318052.

**Comment by starbelly** [comment]
Pretty sure it's going to be per https://github.com/erlang/rebar3/pull/2555 , but not 💯 sure.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... what do you mean broken? Let me check.

**Comment by wojtekmach** [comment]
> Pretty sure it's going to be per erlang/rebar3#2555 , but not 💯 sure.

that's not it, I'm explicitly setting the rebar3 version.

> Hm... what do you mean broken? Let me check.

Please check the build failure.

**Comment by paulo-ferraz-oliveira** [comment]
It's saying rebar3 is not found in the release listing... 🤔

**Comment by wojtekmach** [comment]
oh good catch, I was looking at the wrong error

**Comment by paulo-ferraz-oliveira** [comment]
This is where we fetch the release info: https://api.github.com/repos/erlang/rebar3/releases.

Unexpectedly 3.6.1 is no longer found there.

**Comment by starbelly** [comment]
> oh good catch, I was looking at the wrong error

So was I :)

**Comment by wojtekmach** [comment]
ah, I know what this is. The API is paginated, we'll find 3.6.1 on page 2:

https://api.github.com/repos/erlang/rebar3/releases?page=2

**Comment by paulo-ferraz-oliveira** [comment]
Ah, you found it also. Unless we want to handle pagination, I'd say 100 latest releases for any given thing we're using, should be enough, no? Erlang, Elixir, rebar3? You tell me.

**Comment by paulo-ferraz-oliveira** [comment]
@wojtekmach, want me to fix it (the quick+dirty way =100), or do you wanna have fun with pagination also? 😄

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira I agree, just use per_page=100

**Comment by paulo-ferraz-oliveira** [comment]
And wow, 3.6.1 was already more that 30 releases ago. 🎉

**Comment by starbelly** [comment]
I'd have to go back and look at the code, but I suspect the rationale behind hitting the api and getting a listing is so that we don't try to download if you specify a version that simply doesn't exist. If we just try to download and it fails though, we could have an error message say something like "Maybe it failed because X or Y or Z".

**Comment by paulo-ferraz-oliveira** [comment]
> I'd have to go back and look at the code, but I suspect the rationale behind hitting the api and getting a listing is so that we don't try to download if you specify a version that simply doesn't exist. If we just try to download and it fails though, we could have an error message say something like "Maybe it failed because X or Y or Z".

This is correct, for the current version.

As per a previous discussion with @ericmj, though, I would also be Ok to drop the "version ranges", but in that case, to make it backward compatible we either break to v2 or we add an option "strict-version: true" and explain what it is in the README. If we decide on no-ranges, at all, we most likely won't even need JavaScript. 😄

**Comment by paulo-ferraz-oliveira** [comment]
> Note that didn't happen in this case obviously :)

It did: the message might not be super clear (and we can work on that), but look here: https://github.com/wojtekmach/test_erlang/pull/1/checks?check_run_id=2686501028#step:2:12.

What is wrong, here, also, is that that step isn't stopping the build earlier. Let me open a issue for that.

**Comment by wojtekmach** [comment]
what would strict-version do? you either specify major.minor.patch or you don't and in the latter case you have a version range.

**Comment by paulo-ferraz-oliveira** [comment]
`strict` would not care about ranges. e.g. 24.0 would not be `>=24.0.0 <25.0.0-0`, but that can be solved later, though.

**Comment by paulo-ferraz-oliveira** [comment]
☝️ there, that should fix it.

**Comment by wojtekmach** [comment]
Yes it does, I just verified your patch on hex_core. Thanks!

**Comment by starbelly** [comment]
@wojtekmach You should be able to use `@v1` etc. now.

**Comment by wojtekmach** [comment]
yup, thanks!
