### ISSUE TITLE
With .../ubuntu-20.04/builds.txt 503'ing error message is out of scope

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#44]
The error you get is not from the fact the file is not available, which it should be, but further down the execution, by stating the version is not found in the listing.

When trying to download whatever file or fetching whatever external dependency we shouldn't hide errors behind default return values, meaning we should crash whenever https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js#L272 is invoked.

**Comment by josevalim** [comment]
FWIW, there is a fast.ly outage and that may be affecting hex.pm, so we may be seeing error paths that are not common being exercised.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, José. Yeah, Eric told me about it on Slack.

The issue, for me, is the error message itself. 😄

"Erlang 23.3 not found in version listing" (as-is) vs. "Couldn't fetch version listing. Server returned ..." (as I'd propose for the future).
