### ISSUE TITLE
Cannot specify Erlang patch versions

### ISSUE THREAD

**Issue by eproxus** [erlef/setup-beam#46]
Erlang versions uses versions of the form ` MAJOR.MINOR.PATCH.EXTRA1.EXTRA1-PRERELASE`. That is two additional components in addition to normal semver style. Examples:

* 24.0-rc3
* 24.0
* 23.3.4
* 22.3.4.12.1

Currently, when you specify a more fuzzy Erlang version, e.g. `23`, you get the highest matching semver version (`23.3.4`) and not the actual latest patched version (`23.3.4.2`).

**Comment by paulo-ferraz-oliveira** [comment]
We can maybe "trick" the semver lib. by assuming a specific input for OTP versions (as you mention) and transforming it into valid semver (e.g. using pre-releases)... to be studied...

@eproxus, can you point to the OTP versioning reference? I can't seem to find it easily using "The Search Engine".

Thanks.

**Comment by garazdawi** [comment]
http://erlang.org/doc/system_principles/versions.html

**Comment by eproxus** [comment]
So below semver it can get really tricky:

> The version 6.0.2.1 will include all changes in 6.0.2. However, 6.0.3 will most likely not include all changes in 6.0.2.1 (note that these versions have no order). A second branched version from the base version 6.0.2 will be version 6.0.2.0.1, and a third branched version will be 6.0.2.0.0.1.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, it gets hairy. But we can probably work something out for certain corner cases, even if we have to use extra options (like the `strict/loose` option I talked about earlier, on Slack). With `strict`, 24 would fail, since it doesn't exist, but also with `strict` 24.0 would not be translated into the max. satisfying version of a range, like 24.0.2. Thoughts?

**Comment by eproxus** [comment]
Use the "normal" `=` or `>=` `~=` prefixes maybe?

**Comment by paulo-ferraz-oliveira** [comment]
> Use the "normal" `=` or `>=` `~=` prefixes maybe?

For what? I didn't get the suggestions.

FYI: we're using a lib. for the `semver` stuff. If we stop using it, we have to rethink the support for version ranges, which is something I'd prefer not to dive into. But we can try to "fake" it...

**Comment by eproxus** [comment]
I meant instead of a strict/loose mode (i.e. instead of `strict` a user has to write `= 24.0` or instead of `loose` you'd say `~= 24`). But yeah, I don't know how you implement it so I can't speak for how easy it is.

**Comment by paulo-ferraz-oliveira** [comment]
> I meant instead of a strict/loose mode (i.e. instead of `strict` a user has to write `= 24.0` or instead of `loose` you'd say `~= 24`). But yeah, I don't know how you implement it so I can't speak for how easy it is.

Thing is the string is itself already interpreted, so '>24' (as passed to `semver` already has meaning). I think `strict` will be used in very restricted use cases, and will not be the norm.
