### ISSUE TITLE
Add additional problem matchers for third party projects

### ISSUE THREAD

**Issue by btkostner** [erlef/setup-beam#62]
Right now this `setup-beam` action has a couple of [problem matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) already [being installed](https://github.com/erlef/setup-beam/blob/main/.github/elixir-matchers.json). Would you accept PRs for some notable third party projects?

What is already installed:
- Elixir compiler errors
- Elixir compiler warnings
- Elixir mix test failures

What I would like to add:
- [Credo](https://github.com/rrrene/credo) (see https://github.com/rrrene/credo/pull/870) 
- [dialyzer](https://erlang.org/doc/man/dialyzer.html)

I'm not 100% sure if it's possible for the above, but I wanted to know if they would be accepted before attempting to make some working versions.

**Comment by paulo-ferraz-oliveira** [comment]
I'm not against it, in principle.

If you do move forward do add some tests, please.

**Comment by btkostner** [comment]
Closing this issue now that tests have been added and https://github.com/erlef/setup-beam/pull/65 will add problem matchers for Credo and Dialyzer. Thank you for the answer!
