### ISSUE TITLE
Support non-tagged rebar3 versions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#68]
As-is we're incapable of targeting the most recent non-tagged development commit, which could be useful for nightly CI as a way to preemptively detect upcoming issues. Should we do this? The only issue I haven't solved is "how" we'd fetch the version. We could go with a fixed string, eg. latest/main/... that we'd fetch if no tagged version was found (hopefully there'll never be a tag with the development branch's name).

An idea we might borrow from gleam-lang/setup-gleam is the use of `ref:main` as a way to "clone" from a ref and not fetch a given tagged element.

**Comment by paulo-ferraz-oliveira** [comment]
Upon thinking further, this would imply (to not have to deal with building on our side) that a version would be released for HEAD every time it would be updated, which is not the case. Gleam does it via asdf or homebrew, which is a different process than the one we're using.

**Comment by paulo-ferraz-oliveira** [comment]
Actually (re-opening) something like `ref:master` could pull directly from `s3://rebar3-nightly` which is where the edge is found.

**Comment by starbelly** [comment]
I think being able to pull in master or nightly is a great idea. Some people run (or would run) CI builds regularly to make sure a lib, plugin, or code base works with the latest changes in rebar3. It's all around good for the community IMO.

**Comment by paulo-ferraz-oliveira** [comment]
Agree. I open and closed then thought about it and opened again. Let's see what the kind folks at Gleam say about that, too (?)
