### ISSUE TITLE
Build is failing per third-party license differences 

### ISSUE THREAD

**Issue by starbelly** [erlef/setup-beam#76]
See https://github.com/erlef/setup-beam/runs/4572138656?check_suite_focus=true as an example.

**Comment by paulo-ferraz-oliveira** [comment]
Hey.

You have to check the actions (I think it's `npm run licenses`) to update this locally, after which you have to upload the differences too.

We should probably have a "How to contribute" part in the README because some details (like this) aren't immediately obvious.

**Comment by starbelly** [comment]
Yeah, I knew that part but I wasn't sure why there was a diff all of a sudden, I guess it just grabbed some latest versions in ci.

**Comment by paulo-ferraz-oliveira** [comment]
That's the main part of it I don't like (this whole licensing thing - we inherited it, we didn't come up with it). This only proves that even for a given fixed version there are some internal moving parts (mostly some JS lib.).

Should we try to automate the update of that file? I'm sure whoever's doing it is not validating ALL the updates licenses one by one.

**Comment by starbelly** [comment]
Well, I guess the question I ask myself is what do we get out of checking the licenses? I think perhaps made since when github owned the action as setup-elixir, but I don't think it makes sense for us.

**Comment by paulo-ferraz-oliveira** [comment]
We check the licenses to make sure they're updated (as per the version we're pulling). Otherwise you might be importing a version of a dep. that has a non-proper (updated) license. This only happens when the license changes (or is added or removed), I imagine. But I'm Ok with whatever is decided for this. No real opinion on having the licenses declared or not (don't know if it's a legal requirement).

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, do you think it's relevant to keep the generated 3rd party licenses next to the software? I mean, I don't see this being done often, but there might be good reason for this to have happened from the get-go.

If not, we should get rid of everything 3rd party license -related and avoid this class of issues.

**Comment by starbelly** [comment]
Actually yeah, per the licenses of some of the third party deps, they must be included since pulling down the action from github ci is considered distribution.

**Comment by paulo-ferraz-oliveira** [comment]
Ok, do you know how to automate this? 😄 I mean, we can always do it just before a release, but if automatic, it would probably be better.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira Yeah, I think it's best if done before a release to ease the friction. We could setup scheduled builds to keep us in check.

**Comment by paulo-ferraz-oliveira** [comment]
> We could setup scheduled builds to keep us in check.

Does this mean "send us an email", or something? I've not used that before.

**Comment by starbelly** [comment]
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule
