### ISSUE TITLE
Allow disabling problem matchers

### ISSUE THREAD

**Issue by hauleth** [erlef/setup-beam#77]
This is useful in 2 situations:

1. When you test against multiple Elixir/Erlang versions and you want to mark which one should produce the messages.
2. When you use alternative approach to producing the reports (for example [`mix_machine`](https://github.com/hauleth/mix_machine)) and you do not want to have duplicated messages.

This could be simple boolean flag `enable_problem_matchers` that would default to `true`, but it would allow power-users to disable such behaviour.

**Comment by paulo-ferraz-oliveira** [comment]
Cool. We are accepting pull requests 😄 and I do agree with your approach.
