### ISSUE TITLE
Is it possible to support ArchLinux?

### ISSUE THREAD

**Issue by armanm** [erlef/setup-beam#78]
I would like to use ArchLinux and this action does not seem to support Arch as of now.

Could this be done? if someone could point me to some instructions I'm happy to present a PR. Just not sure if I'm the best person for it.

**Comment by starbelly** [comment]
Hey @armanm I think that's going to be a question for @wojtekmach or @ericmj who are responsible for the builds setup-beam pulls from. 

You might want to open an adjacent issue on https://github.com/hexpm/bob/issues

**Comment by armanm** [comment]
Thanks @starbelly 

@ericmj's response in https://github.com/hexpm/bob/issues/83#issuecomment-814834635 pretty much answers my question. 

> Adding a new OS requires building thousands of images so it's something we want to hold off with until there are enough that need it.

I'm going to close this
