### ISSUE TITLE
Does this action support ubuntu on arm64 architecture ?

### ISSUE THREAD

**Issue by gsmlg** [erlef/setup-beam#96]
Does this action support ubuntu on arm64 architecture ?

**Comment by starbelly** [comment]
Not currently. The builds of OTP pulled in currently are x86. We can discuss with others if we could start doing arm64 builds, but another issue is github does not have hosted arm64 runners. So you would need to either host your own runner (arm64 build) or use Github AE (which I believe has hosted arm64 runners).

**Comment by gsmlg** [comment]
Thanks, I've got this.
