### ISSUE TITLE
Error installing rebar3

### ISSUE THREAD

**Issue by hermanius** [erlef/setup-beam#99]
Using the following:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]

I get the following error:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/16594513/161158262-a13a5dd8-7058-46b4-8539-9e37917dddd9.png">

Am I doing something wrong?

**Comment by hermanius** [comment]
The error stays, even if I add `install-rebar: false`

**Comment by paulo-ferraz-oliveira** [comment]
Hm... let me test this.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/paulo-ferraz-oliveira/setup-beam-example/blob/setup-beam/issues/99/.github/workflows/ci.yml

Is this the same as your example? I don't see it error'ing out (maybe I'm missing something?)

Initially I thought it could be from the v3 (for the `checkouts` action), but seems not to be so.

**Comment by paulo-ferraz-oliveira** [comment]
In particular, I have https://github.com/paulo-ferraz-oliveira/setup-beam-example/runs/5821121108?check_suite_focus=true#step:3:24, which seems to be different from your output.

**Comment by hermanius** [comment]
hmmm, strange, I still have the same error. It has worked before, and suddenly stopped working, without any hanges in the yaml file. And the yaml files seems to look the same.
Is it an idea to give you temporarily access to the repository where I have the problem?

**Comment by paulo-ferraz-oliveira** [comment]
I can fork it and test it out (if I know where stuff is), but I see no real reason for this to fail, atm.

Can you copy-paste from my example repo. and test again?

**Comment by hermanius** [comment]
I tried the copy-paste, and only changed the on: push to on:workflow_dispatch, and I still get the same error.

I have send you an invite to collaborate on my private repository. It would be great if you have the time to check it out.

**Comment by paulo-ferraz-oliveira** [comment]
> even if I add `install-rebar: false`

seems like an action issue, since it shouldn't try to install stuff we told it not to.

**Comment by paulo-ferraz-oliveira** [comment]
@hermanius, after the fix proposed by #100 (still needs discussion and merge), using `install-hex: false` and `install-rebar: false` means that the action already runs past the installation part (in your case), but I still can't understand why it fails otherwise. The only difference I see is that your repo. is private, but I'm not sure how that would influence it. (I actually went ahead, created a private repo and tested this: still no issue!). I'm not sure why the Elixir function is getting `nil` instead of a `binary()` 🤷

**Comment by hermanius** [comment]
@paulo-ferraz-oliveira , I really appreciate the effort you are doing to find a solution. It's a curious issue indeed, and even stranger is that it worked for a few days, and then suddenly stopped working. As if Github has made a change somewhere.
At some point I'm going to need hex/rebar so I hope, after the fix, I can get them installed later in the workflow using RUN commands. Getting them installed through your action still would be the preferred solution, but if I can do it with a few RUN commands it would be a decent work-around.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I'm sorry I can't help further. I can ask @ericmj for help, since this is Elixir and he probably knows where the issue is apparent, but not what is causing it. Close at will if you feel this is no longer an issue.

**Comment by hermanius** [comment]
I'm hoping #100 gets approved soon, so I can see wether I can install hex/rebar with RUN commands.

**Comment by hermanius** [comment]
I was able to run the workflow with paulo-ferraz-oliveira/setup-beam@fix/booleans and install rebar/hex with RUN's further down the workflow.
For me this a good-enough work-around, and I hope of course you will be able to fix the issue someday.
Thanks for helping me out.

**Comment by paulo-ferraz-oliveira** [comment]
@hermanius, [1.11.1](https://github.com/erlef/setup-beam/releases/tag/v1.11.1) is released. Cheers.
